### PR TITLE
mysql: update to 5.7.27

### LINKED ISSUE #1068: Upgrade Mysql to 5.7.27
https://github.com/mysql/mysql-server/releases/tag/mysql-5.7.27

### PR DESCRIPTION
**Pull request by kyrofa**
This PR resolves #1068 by updating MySQL to the latest 5.7 release.

### CODE REVIEW

**Comment by stondino00** [comment]
Can this be updated in the 16/candidate channel as well?

**Comment by kyrofa** [comment]
Just testing this as a fresh install as well as an upgrade, all looks good.

**Comment by kyrofa** [comment]
> Can this be updated in the 16/candidate channel as well?

It'll be there eventually, yes, but probably not in the most timely of manners.

**Comment by stondino00** [comment]
Seems like we are now in limbo who have upgraded to 16/candidate and want to stay there AND keep dependencies up to date.  Should I make a PR with 16.03 and Mysql 5.7.27 in the meantime?

**Comment by kyrofa** [comment]
Yes, stable releases (`stable`, `15/stable`, there's a reason there is no `16/stable`) are the only ones we can reliably test and support. Proposing such a change would have no destination (you'll notice `master` and `develop` are both still on v15)-- v16 builds are all manual one-offs right now.

To be fair, I haven't made that very clear with people wanting to use v16, so I'll see what I can do.

**Comment by stondino00** [comment]
No worries that all makes sense.  For my reasons version 16 had many bundled security updates that 15 doesn't have and came up during web app vulnerability scans.

**Comment by kyrofa** [comment]
Alright, 16.0.3snap1rc2 is rolling out to `16/candidate` now with both mysql and php updates.

**Comment by stondino00** [comment]
Awesome

I've refreshed the snap and all is showing good.

Thanks so much!

**Pull request merged**
