### PR TITLE
occ: add apices for arguments

### PR DESCRIPTION
**Pull request by 3v1n0**
Without this we end up in this issue:
 - https://github.com/nextcloud/server/issues/4291

### CODE REVIEW

**Comment by kyrofa** [comment]
Oh man, this is old. We probably want "$@", don't you agree?

**Comment by 3v1n0** [comment]
Agree... And done.

**Comment by kyrofa** [comment]
Sorry, just noticed this was going to master-- please squash into a single commit and target to develop instead.

**Comment by kyrofa** [comment]
I'll go ahead and close this, thanks @3v1n0.

**Pull request closed without merging**
