### PR TITLE
nextcloud: update to 16.0.6

### LINKED ISSUE #1164: Upgrade NextCloud to 16.0.7
https://github.com/nextcloud/server/releases/tag/v16.0.6

### PR DESCRIPTION
**Pull request by kyrofa**
This PR resolves #1164 by updating Nextcloud to the latest v16 release.

### CODE REVIEW

**Comment by pachulo** [comment]
Tried to refresh my instance with:
`sudo snap refresh nextcloud --channel=beta/pr-11166`
but it seems that this is not yet published.

**Comment by pachulo** [comment]
A fresh install of this on my amd64 laptop did work OK.

**Comment by derhagen** [comment]
@kyrofa looks like the snap builder died

**Comment by kyrofa** [comment]
Hmm, on an upgrade, I see this:

```
Nov 19 09:12:47 protege nextcloud.apache[13557]: Checking for update of app files_rightclick in appstore
Nov 19 09:12:47 protege nextcloud.apache[13557]: Update app files_rightclick from appstore
Nov 19 09:12:48 protege nextcloud.apache[13557]: Checked for update of app "files_rightclick" in appstore
```

But after the upgrade completes, when I visit Nextcloud I see this:

Screenshot from 2019-11-19 09-14-18

Can anyone else confirm?

**Comment by kyrofa** [comment]
> looks like the snap builder died

If you look at the log you'll see that it actually released, but something is wonky indeed.

**Comment by kyrofa** [comment]
> But after the upgrade completes, when I visit Nextcloud I see this:

If you restart the snap (`sudo snap restart nextcloud`) you'll actually see the upgrade happen AGAIN, despite having already run successfully. Something is broken here.

**Comment by kyrofa** [comment]
I added some detailed notes here: https://github.com/nextcloud/server/issues/17338

**Comment by derhagen** [comment]
@kyrofa looks like the `beta/pr-1166` was closed automatically. Thus, my instance fell back to `beta`, showing
``` Downgrading is not supported and is likely to cause unpredictable issues (from 16.0.6.1 to 16.0.5.1) ``` rendering my instance unusable.
Can you please reactivate the channel or give me a hint how to get back on 16.0.6 again, with my snap?

**Comment by derhagen** [comment]
> Can you please [...] give me a hint how to get back on 16.0.6 again, with my snap?

`snap revert nextcloud` did the trick. However, it was kind of unexpected for me that (a) the pr-channel got automatically closed before being merged and (b) that my instance automatically switches to the beta-channel, which was a downgrade in this case, making my instance unusable.

**Comment by stondino00** [comment]
https://github.com/nextcloud/server/releases/tag/v16.0.7

https://nextcloud.com/blog/nextcloud-17-0-2-16-0-7-and-15-0-14-available-for-update-plus-beta-3-of-18-for-testing/

**Comment by stondino00** [comment]
Security updates for PHP 7.2 and 7.3.  Not sure if this PR can be built with either 7.2.26 OR 7.3.13 that fixes PHP vulnerabilities and Nextcloud 16.0.7.

**Comment by stondino00** [comment]
Any update on this 16.0.7 and an updated php version for security?

**Comment by kesselb** [comment]
Should be fixed by: https://github.com/nextcloud/server/pull/18259

Adding the app to `shipped.json` will prevent the update from app store.

**Comment by pachulo** [comment]
@kesselb did you try to upgrade from the `16.0.5snap3` to the version you created here https://github.com/nextcloud/nextcloud-snap/pull/1198 ? Because @kyrofa backported the fix you mention, but he said that it was not sufficient to solve the issue: https://github.com/nextcloud/nextcloud-snap/issues/1129#issuecomment-567262674

**Comment by kesselb** [comment]
> backported the fix you mention, but he said that it was not sufficient to solve the issue:

He is right.

**Pull request closed without merging**
