### PR TITLE
Release 14.0.6snap1

### PR DESCRIPTION
**Pull request by kyrofa**
- php: enable large file support on 32-bit systems
- nextcloud: update to 14.0.6
- php: update to 7.2.14

Please test this PR using the `candidate` channel:

    $ sudo snap install --candidate nextcloud

Or, if you already have it installed:

    $ sudo snap refresh --candidate nextcloud

### CODE REVIEW

**Comment by pachulo** [comment]
I guess is already too late to squash my 3 commits for the PHP upgrade, isn't it?

**Comment by kyrofa** [comment]
Yeah don't worry about it, that was my mistake :) .

**Comment by kyrofa** [comment]
Please test this PR using the `candidate` channel:

    $ sudo snap install --candidate nextcloud

Or, if you already have it installed:

    $ sudo snap refresh --candidate nextcloud

**Comment by kyrofa** [comment]
This works well for me, fresh install and upgrade.

**Comment by pachulo** [comment]
I upgraded my instance and everything looks fine!

**Pull request merged**
