### PR TITLE
php: update to 7.1.13

### LINKED ISSUE #154: Update PHP to 7.1

### PR DESCRIPTION
**Pull request by pachulo**
Resolve #154

### CODE REVIEW

**Comment by kyrofa** [comment]
Looks good on the surface. I'm spinning up some builds to use for testing.

**Comment by kyrofa** [comment]
Alright, to test this PR, use the `stable/pr-399` channel:

    $ sudo snap install nextcloud --channel=stable/pr-399

Or, if you already have it installed:

    $ sudo snap refresh nextcloud --channel=stable/pr-399

**Comment by pachulo** [comment]
Did the refresh in my rbpi3 and everything is working as expected!
Beforehand I tried a clean installation in my laptop, where everything seemed OK too.

**Comment by pachulo** [comment]
We should check this: https://help.nextcloud.com/t/php-error-narrowing-occurred-during-type-inference/24010/15

**Comment by kyrofa** [comment]
Good catch @pachulo, perhaps we should pause this PR until the 7.1.13 is released. Should be soon, I suspect.

**Comment by pachulo** [comment]
Yeah, I've just checked and my log is full with those messages. I will modify this one the new version is around.

**Comment by pachulo** [comment]
Updated the commit to use PHP 7.1.13. @kyrofa could you spin another build of this PR to see if the problem is real gone?

**Comment by kyrofa** [comment]
Awesome @pachulo, thank you! Unfortunately the build farm is only partially available while Meltdown/Spectre mitigations are rolling, but I'll get this built as soon as I can.

**Comment by pachulo** [comment]
Can we have this now then @kyrofa ?

**Comment by kyrofa** [comment]
Yep, we already have amd64 and i386 if you want to test it out, waiting on the arm builds...

**Comment by kyrofa** [comment]
Alright, arms are up as well. Give it a test!

**Comment by pachulo** [comment]
Installed with no problems and now it seems that the problem with the logs is resolved!

**Comment by kyrofa** [comment]
Awesome @pachulo, thank you. Do me one favor in this PR and I'll merge it: update the README to say that it uses PHP 7.1 instead of just 7.

**Comment by kyrofa** [comment]
(nevermind, I got it, easy tweak)

**Pull request merged**
