### PR TITLE
Add samba client support

### LINKED ISSUE #60: Add samba (smb) support
Adding the samba client to PHP would make it possible to access other storage located on the same network.

### PR DESCRIPTION
**Pull request by pachulo**
With libsmbclient-php, libsmbclient and smbclient.

Right now is building OK and Samba support is available in the external storage application, but when I try connect to a shared folder it does not work.

In the logs I can see those messages:

```
# tail -1 /var/snap/nextcloud/x1/apache/logs/php_errors.log
[26-May-2018 17:37:04 UTC] PHP Warning:  PHP Startup: Unable to load dynamic library '/snap/nextcloud/x1/lib/php/extensions/no-debug-non-zts-20160303/smbclient.so' - libtalloc-report.so.0: cannot open shared object file: No such file or directory in Unknown on line 0
```

The messages in the nextcloud logging are similar:

```
PHP Startup: Unable to load dynamic library '/snap/nextcloud/x1/lib/php/extensions/no-debug-non-zts-20160303/smbclient.so' - libtalloc-report.so.0: cannot open shared object file: No such file or directory at Unknown#0
```

But, as far as I can tell, it should work:

```
# ls -lisah /snap/nextcloud/x1/lib/php/extensions/no-debug-non-zts-20160303/smbclient.so
16306 201K -rwxr-xr-x 1 root root 201K mai 26 18:20 /snap/nextcloud/x1/lib/php/extensions/no-debug-non-zts-20160303/smbclient.so
```

```
# ldd /snap/nextcloud/x1/lib/php/extensions/no-debug-non-zts-20160303/smbclient.so | grep talloc-report
        libtalloc-report.so.0 => /usr/lib/x86_64-linux-gnu/samba/libtalloc-report.so.0 (0x00007fd0ed61c000)
```

```
# ls -lisah /usr/lib/x86_64-linux-gnu/samba/libtalloc-report.so.0
7603550 12K -rw-r--r-- 1 root root 10K mar  7 11:43 /usr/lib/x86_64-linux-gnu/samba/libtalloc-report.so.0
```

Any ideas why this is failling @kyrofa ?

When working, this will fix #60

### CODE REVIEW

**Comment by kyrofa** [comment]
@pachulo libtalloc-report.so.0 needs to be in the snap-- is it not?

**Comment by kyrofa** [comment]
Yes it should: is it there? If so, it's certainly an `LD_LIBRARY_PATH` issue. To check, try adding this YAML snippet to the php fpm app definition (just for testing):

```yaml
environment:
  LD_LIBRARY_PATH: $SNAP/usr/lib/x86_64-linux-gnu/samba
```

**Comment by pachulo** [comment]
Yes, I can confirm it is:
```
$ find /snap/nextcloud/ -iname libtalloc-report.so.0
/snap/nextcloud/x1/usr/lib/x86_64-linux-gnu/samba/libtalloc-report.so.0
```
I will try what you say.

**Comment by pachulo** [comment]
Well, compiled it with the new options, installed, and now I'm getting the same WARNING in the php_errors.log file:

```
$ sudo grep libtalloc /var/snap/nextcloud/x1/apache/logs/php_errors.log
[31-May-2018 10:34:32 UTC] PHP Warning:  PHP Startup: Unable to load dynamic library '/snap/nextcloud/x1/lib/php/extensions/no-debug-non-zts-20160303/smbclient.so' - libtalloc-report.so.0: cannot open shared object file: No such file or directory in Unknown on line 0
```

But I'm not getting errors in the nextcloud logging and SMB shares are working! What should we do now then?

**Comment by r4co0n** [comment]
Please note that the error is not exactly the same, the path where `libtalloc-report.so.0` is expected differs, we got:
```
/snap/nextcloud/x1/usr/lib/x86_64-linux-gnu/samba/libtalloc-report.so.0
/snap/nextcloud/x1/lib/php/extensions/no-debug-non-zts-20160303/smbclient.so
```
If I'm not mistaken, your `find` should have discovered both if they were there.

We might get away by adding a symlink, though understanding why this is happening in the first place and what we are expected to do here is certainly preferable.

**Comment by pachulo** [comment]
Meanwhile I've tried this on my rasbpberrypi and it does not work: it looks like the same problem that we had one year ago, the samba shares functionality works for amd64 but not for armhf, but I'm not able to find out why...no error messages in the logs whatsoever.

Anybody has any ideas on how to try to debug this?

**Comment by kyrofa** [comment]
Darn :( .

**Comment by kyrofa** [comment]
Oh wait, @pachulo you're using an amd64-specific LD_LIBRARY_PATH, that definitely won't work on arm. Let me tweak this a little and have you test it again on arm.

**Comment by pachulo** [comment]
Damm! How could I miss that :(
Anyway, do you know if the reason we have to add this is something related to how snapcraft works or something else?

**Comment by kyrofa** [comment]
It's because `samba-libs` (a dependency being pulled in now) unpacks a ton of libs into `/usr/lib/x86_64-linux-gnu/samba/`. That `samba` subdirectory isn't searched by snapcraft by default, so your `environment` hack made it do so. We just need to make that work a bit better.

**Comment by kyrofa** [comment]
@pachulo okay, take a look at the commit I just added. Try that out on armhf.

**Comment by pachulo** [comment]
OK, I will try. By the way, @kyrofa have you seen the error that made the last step from CI test fail?

```
#!/bin/bash -eo pipefail
sudo snap install *.snap --dangerous
sudo nextcloud.manual-install admin admin
error: cannot perform the following tasks:
- Run configure hook of "nextcloud" snap if present (run hook "configure": /snap/nextcloud/x1/meta/hooks/configure: 5: export: :/snap/nextcloud/x1/lib:/snap/nextcloud/x1/usr/lib:/snap/nextcloud/x1/lib/x86_64-linux-gnu:/snap/nextcloud/x1/usr/lib/x86_64-linux-gnu: bad variable name)
Exited with code 1
```

**Comment by kyrofa** [comment]
Huh, it's a [snapd bug](https://github.com/snapcore/snapd/pull/5302). Guess we'll need to put this in a wrapper for now.

**Comment by pachulo** [comment]
@kyrofa should this work now with snapd 2.33.1 without a wrapper? As per your fix being included in it: https://forum.snapcraft.io/t/snapd-2-33-release-cycle-started/5585/5

**Comment by kyrofa** [comment]
@pachulo indeed, shall we wait?

**Comment by pachulo** [comment]
@kyrofa refreshed core 2.33.1 and then refreshed nextcloud with the one compiled from this branch.

Now I'm not seeing any `Unable to load dynamic library` messages, but the Samba shares still does not work (remember I'm talking about my raspberrypi3 instance).

The only errors I can see now are these:
```
root@localhost:/home/pachulo# tail -f /var/snap/nextcloud/x1/apache/logs/* 
==> /var/snap/nextcloud/x1/apache/logs/error_log <==
[Sun Jun 24 12:21:23.654414 2018] [proxy_fcgi:error] [pid 13306:tid 1836053552] [client X.X.X.X:44640] AH01067: Failed to read FastCGI header
[Sun Jun 24 12:21:23.654584 2018] [proxy_fcgi:error] [pid 13306:tid 1836053552] (104)Connection reset by peer: [client X.X.X.X:44640] AH01075: Error dispatching request to : 
```

And:
```
$ sudo less /var/snap/nextcloud/x1/php/php-fpm.log
[24-Jun-2018 12:39:37] WARNING: [pool www] child 16863 exited on signal 11 (SIGSEGV) after 15.970333 seconds from start
[24-Jun-2018 12:39:37] NOTICE: [pool www] child 16881 started
```

Each one of those gets logged everytime I try to configure a SMB share.

By the way, the response I'm getting from the nextcloud server to the PUT request is a 503.

**Comment by vinylourson** [comment]
Hi folks, any chance for the merging to happen anytime soon? The SMB / CIFS external storage support is what I needed for a project.
Well, guess I'll have to install nextcloud the "traditionnal" :-/ in the meantime...

**Comment by fishscene** [comment]
The last update was almost a year ago. What is the current status of this? Or is it still on the roadmap for inclusion in the SNAP?

Thanks guys for your hard work on this. I for one am looking forward to samba support in the SNAP.
:)

**Comment by kyrofa** [comment]
@fishscene we'd love to, we just can't seem to get it working properly. Still something we'd love to get, we just have limited time for brick walls like this. If anyone has any ideas or time to poke around, definitely would like to get this in.

**Comment by fishscene** [comment]
@kyrofa Thanks for the insight.

I did dig up this which may or may not provide insight:
https://github.com/oerdnj/deb.sury.org/issues/628
In sum, with a similar issue to what @pachulo was seeing, it turned out to be a conflict between gmagick and imagick.

However, at this point, I'm not sure if I'm adding noise or actually being helpful as my expertise in this sort of thing is quite lacking.

**Comment by kyrofa** [comment]
This is old. Closing due to inactivity. This functionality is still definitely desired, but we haven't managed to make it work everywhere yet. Contributions definitely welcome.

**Pull request closed without merging**
