### PR TITLE
Release 12.0.4snap1

### PR DESCRIPTION
**Pull request by kyrofa**
- nextcloud: update to 12.0.4
- php: update to 7.0.25
- CI: test daily snaps on a daily basis

Please test this release by using the candidate channel:

    $ sudo snap install --candidate nextcloud

Or if you already have it installed:

    $ sudo snap refresh --candidate nextcloud

If you're up for helping out with some [smoke tests for various features](https://github.com/nextcloud/nextcloud-snap/wiki/Smoke-Tests), I would love you forever.

### CODE REVIEW

**Comment by lancezhou** [comment]
I can not update  app(calendar, note, task ...) with this version(v12) online.

**Comment by pachulo** [comment]
hey @lancezhou ! how are you trying to update them? Are you seeing any error? I upgraded this week and the apps updated OK.

**Comment by kyrofa** [comment]
Yeah, please give more details @lancezhou.

**Comment by lancezhou** [comment]
@pachulo @kyrofa 
Firstly, I did upgrade by `$ sudo snap refresh --candidate nextcloud`.
Then I tried with`$ sudo snap install --candidate nextcloud` , after fail with app's upgrade.
Process was completely fine ,both of them.
My situation is connecting busy which new apps enable or upgrade. some message here.
`cURL error 7: Failed to connect to github-production-release-asset-2e65be.s3.amazonaws.com port 443: Connection timed out`

**Comment by FoxBJK** [comment]
I ran through this update this afternoon, but I can't access my install anymore. I was using a custom port, not sure if that would've been reverted. From what I can tell, NextCloud is still running (see attached). Does something need to be reconfigured to work again?

screen shot 2017-12-11 at 1 21 54 pm

**Comment by kyrofa** [comment]
@FoxBJK no, the upgrade should be seamless, and keep your port settings. Could you please run the script described [here](https://github.com/nextcloud/nextcloud-snap/wiki/Issue-Debugging-Scripts) to obtain some logs for us?

**Comment by kyrofa** [comment]
@lancezhou I genuinely have no idea what that URL is. It's not in the Nextcloud tarball, so it must be related to an app. Your issue does not seem related to the upgrade to v12.

**Comment by FoxBJK** [comment]
Looks like apache isn't starting. Not sure why, but investigating. I run a lot of things on this box (ubuntu server) but nothing should be interfering with this.

[debug.txt](https://github.com/nextcloud/nextcloud-snap/files/1548967/debug.txt)

**Comment by kyrofa** [comment]
@FoxBJK yeah looks like it's trying to bind to port 80, which is taken. What is `sudo snap get nextcloud ports` say?

**Comment by FoxBJK** [comment]
Ah, well there's the problem. Something else on this box is using port 80 so I'll have to move it again. Once that's done I imagine I'll just restart the apache instance and be good, but I'll come back here and update.

To answer your question, here's what I got:
Key          Value
ports.http   80
ports.https  7070

**Comment by kyrofa** [comment]
Okay very good. I was concerned it somehow wiped your port settings, but it looks like you only changed the HTTPS one? Indeed, that seems to be the issue.

**Comment by FoxBJK** [comment]
I can't find the settings for this other application so I'm trying to update this snap and restart, but it's still not working. I don't use HTTP for this so I don't care what it's set to. I moved it over to 7069, but `systemctl restart snap.nextcloud.apache.service` didn't fix anything.

**Comment by kyrofa** [comment]
Can I see a new log, please?

**Comment by FoxBJK** [comment]
Attached [debug_2.txt](https://github.com/nextcloud/nextcloud-snap/files/1549026/debug_2.txt)

**Comment by FoxBJK** [comment]
Sorry, deleted my last post because the problem exists between the keyboard and the chair. We're good now, and with these new port settings I imagine I should be OK through future upgrades too.

**Comment by kyrofa** [comment]
Huh, that log looks good to me-- everything seems up and running. Are you sure you're visiting it on the right port? It's no longer listening on port 80 to redirect to your non-standard HTTPS port, so you'll need to navigate to one or the other manually.

**Comment by kyrofa** [comment]
Ah ha! Okay very good :grin: .

**Comment by kyrofa** [comment]
@FoxBJK glad you tested, you have a bit of a non-standard setup. I'm feeling more and more confident about this one.

**Comment by FoxBJK** [comment]
Glad I could help! Clients are syncing again so it really seems like the only issue was my non-standard port setup. Multiple things run on this box (ubuntu server 17.04, if that helps) just fine, but lots of them want to default to the same port.

**Comment by kyrofa** [comment]
Alright it's been several days, with several people testing this extensively (including myself on my production instance). I think we're good to go.

**Pull request merged**
