### PR TITLE
Update PHP 7.4.18

### LINKED ISSUE #1712: PHP 7.4.18
Being released tomorrow.  Final already built.

### PR DESCRIPTION
**Pull request by stondino00**
Fixes #1712

### CODE REVIEW

**Comment by stondino00** [comment]
Sorry, this patch I went a bit too quick the first time around when creating it.

**Comment by kyrofa** [comment]
Nah you're good, easy fix. Let's hold off until tomorrow though, make sure they actually release this thing.

**Comment by stondino00** [comment]
Ok they've officially released 7.4.18.

https://www.php.net/ChangeLog-7.php#7.4.18

**Comment by stondino00** [comment]
Develop/beta branch still doesn't appear to be updating when you push commits to it and still need manually done with whatever you do behind the scenes.

Thanks

**Pull request merged**
