### PR TITLE
apache: remove 'includeSubDomains' from HSTS header

### LINKED ISSUE #435: Disable HSTS after certifcate install nextcloud.enable-https lets-encrypt

### PR DESCRIPTION
**Pull request by bn4t**
Fixes #435

### CODE REVIEW

**Comment by r4co0n** [comment]
The `Fixes …` part in the title is not parsed and picked up by GitHub, you should put it in the description, I suppose.

**Comment by bn4t** [comment]
Fixed it. Thank you for the heads up :)

**Comment by kyrofa** [comment]
It actually should be part of both the description and the commit message (from which the default description is generated anyway). That way we know both in review and after the fact the issue that this was supposed to fix. Mind amending this commit?

**Comment by bn4t** [comment]
done :)

**Comment by kyrofa** [comment]
Hmm.... I'm starting to rethink this one as I research it further. Check out [this material](https://www.owasp.org/index.php/HTTP_Strict_Transport_Security_Cheat_Sheet) from owasp:

> Cookies can be manipulated from sub-domains, so omitting the "includeSubDomains" option permits a broad range of cookie-related attacks that HSTS would otherwise prevent by requiring a valid certificate for a subdomain. Ensuring the "Secure Flag" is set on all cookies will also prevent, some, but not all, of the same attacks. 

Knowing that, I doubt this is something we want to just remove for everyone (I certainly want it). Sounds like we need more fine-grained control over this, which makes it quite a bit more work I'm afraid. I'm sorry @bn4t, this PR was nice and simple! Let's chat more about this on the issue, I'll close this for now.

**Pull request closed without merging**
