### PR TITLE
nextcloud: update to 19.0.1

### LINKED ISSUE #1408: Update NextCloud to 19.0.1
https://nextcloud.com/changelog/#latest19

Not sure if there are any outstanding bugs being fixed like last release but 19.0.1 has landed on the change-log page for releases.

### PR DESCRIPTION
**Pull request by kyrofa**
This PR resolves #1408 by updating Nextcloud to the latest v19 release.

### CODE REVIEW

**Comment by kyrofa** [comment]
Snaps of this PR for all architectures are available in the `latest/beta/pr-1410` channel. See the [testing pull requests](https://github.com/nextcloud/nextcloud-snap/wiki/Testing-pull-requests) page for more information on how to test this.

**Comment by kyrofa** [comment]
This seems to work for me, both on fresh install and upgrade from stable.

**Comment by PnjDbq** [comment]
No issues updating from 19 stable.

**Comment by pachulo** [comment]
Everything also fine here after a refresh from stable.

**Comment by theoneandonly-vector** [comment]
I just have another but very similar issue just after updating..
I now have files which have a negative size displayed like (-5591858889 Bytes)

**Pull request merged**
