### PR TITLE
[11] Update version to 11.0.6snap1

### PR DESCRIPTION
**Pull request by kyrofa**
Also update README and CHANGELOG.

Please test this PR using the `11/candidate` channel:

    $ sudo snap install nextcloud --channel=11/candidate

Or if you already have the snap installed:

    $ sudo snap refresh nextcloud --channel=11/candidate

### CODE REVIEW

**Comment by mauriziomarini** [comment]
I get the "Downgrading is not supported and is likely..."  warning message
I can't get login form to access

**Comment by kyrofa** [comment]
@mauriziomarini yeah, don't switch channels from 12 to 11, that's not supported indeed. I suggest you refresh back to stable to stay on v12:

    sudo snap refresh --stable nextcloud

**Comment by mauriziomarini** [comment]
How long it could take to have your fix merged into stable 12.0.4?

**Comment by kyrofa** [comment]
Which fix? This pull request is about upgrading the 11/* channels to v11.0.6 (from v11.0.5). Unless you're on those channels, you probably don't want this :) .

**Pull request merged**
