### PR TITLE
nextcloud: update to v12.0.0

### LINKED ISSUE #280: Update to 12.0
@kyrofa

### PR DESCRIPTION
**Pull request by kyrofa**
This PR resolves #280 by updating Nextcloud to v12.0.0.

Please test this PR with:

```
$ sudo snap install nextcloud --channel=stable/pr-281
```

### CODE REVIEW

**Comment by kyrofa** [comment]
All I've changed here is the Nextcloud version, and I'm seeing this in Firefox:

screenshot from 2017-05-22 20-37-47

I'm not sure where the MIME type mismatch is coming from, all I'm changing here is the Nextcloud version. Anyone have any ideas?

**Comment by pachulo** [comment]
Could it be related to the multiple issues logged?
image

I think that they are related to this issue:
https://github.com/nextcloud/server/issues/5057

**Comment by kyrofa** [comment]
@pachulo yikes, yes! I saw those errors from FF and didn't go any further, but it seems they were a red herring. Great find on the issue! I agree, that looks like it's the problem.

**Comment by kyrofa** [comment]
It seems we're holding out on the upgrade to v12 until a point release.

**Pull request closed without merging**
