### PR TITLE
Upgrade MySQL to 5.7.34

### LINKED ISSUE #1616: MySQL 5.7.33
https://dev.mysql.com/doc/relnotes/mysql/5.7/en/news-5-7-33.html

### LINKED ISSUE #1703: MySQL 5.7.34
https://dev.mysql.com/doc/relnotes/mysql/5.7/en/news-5-7-34.html

Oracle's quarterly security patch

### PR DESCRIPTION
**Pull request by stondino00**
Fixes #1703

### CODE REVIEW

**Comment by stondino00** [comment]
Not sure why she failed in Circleci.

**Comment by stondino00** [comment]
@kyrofa I know your super busy but if you could help us out by getting this pushed to devel and see why that branch isn't updating with the pushed commits, that would be great.

Thanks so much!

**Comment by stondino00** [comment]
Any luck with this @kyrofa ?

**Review by kyrofa — APPROVED** [review]
Looks like a transient failure in circle, I kicked it over. Change looks good to me, thank you!

**Comment by kyrofa** [comment]
For future reference, please put the `Fixes: #<bug ref>` in the commit itself and PR description, not the title.

**Comment by stondino00** [comment]
Awesome

Thanks so much.  I'll remember that on my next patch commit.

**Pull request merged**
