### PR TITLE
nextcloud: update to 13.0.5

### LINKED ISSUE #644: Update nextcloud to 13.0.5
https://nextcloud.com/changelog/#latest13

### PR DESCRIPTION
**Pull request by pachulo**
This PR resolves #644 by updating Nextcloud v13.0.5.

### CODE REVIEW

**Comment by JamesBream** [comment]
This should also resolve this ticket too with any luck https://github.com/nextcloud/nextcloud-snap/issues/631

**Comment by kyrofa** [comment]
Please test this PR using the `beta/pr-649` channel:

    $ sudo snap install nextcloud --channel=beta/pr-649

Or, if you already have it installed:

    $ sudo snap refresh nextcloud --channel=beta/pr-649

Thanks @pachulo!

**Comment by kyrofa** [comment]
@JamesBream mind giving that a test?

**Comment by JamesBream** [comment]
@kyrofa Not seeing any glaring issues here 👍

**Pull request merged**
