### PR TITLE
apache: update to 2.4.26

### LINKED ISSUE #311: Update Apache to 2.4.26
2.4.25 has multiple security vulnerabilities.

### PR DESCRIPTION
**Pull request by kyrofa**
This PR resolves #311 by updating Apache from 2.4.25 to 2.4.26.

Please test this PR by installing the snap from the `stable/pr-312` branch:

    $ sudo snap install nextcloud --channel=stable/pr-312

Or if you already have it installed:

    $ sudo snap refresh nextcloud --channel=stable/pr-312

### CODE REVIEW

**Comment by pachulo** [comment]
It's seems to work OK here too: upgraded my rpi3 instance and everything seems to be as it was.

**Comment by kyrofa** [comment]
Ah, small things break down, i.e. you can't share. Setting `ProxyFCGIBackendType` back to GENERIC makes things work again.

**Comment by pachulo** [comment]
Updated to the new revision on my rpi3 (1911) and the application seems to work OK. I've also did a little test creating a sharing link and it seems to work smoothly.

**Comment by kyrofa** [comment]
Thanks @pachulo :) .

**Pull request merged**
