### PR TITLE
nextcloud: update to v12.0.1

### PR DESCRIPTION
**Pull request by pachulo**
Revolves #280

### CODE REVIEW

**Comment by kyrofa** [comment]
Alright, this PR is now available for testing in the `stable/pr-334` channel:

    $ sudo snap install nextcloud --channel=stable/pr-334

Or, if you already have it installed:

    $ sudo snap refresh nextcloud --channel=stable/pr-334

**Comment by kyrofa** [comment]
Still definitely suffers from https://github.com/nextcloud/server/issues/5532 .  I also can't create new contacts :( .

**Comment by kyrofa** [comment]
Huh... maybe that's just a contacts app issue? https://help.nextcloud.com/t/contacts-addressbook-is-undefined/14262

**Comment by kyrofa** [comment]
Wow, yeah... click the gear icon, create a new addressbook, and THEN you can create new contacts. The UX is dreadful.

**Comment by kyrofa** [comment]
Missing icons here on the left as well:

image

Compare to v11.0.3:

image

**Comment by kyrofa** [comment]
At least both the calendar and contacts pick up the addressbook and default calendar when upgrading from 11.0.3, so that terrible UX will only bite brand new users.

**Comment by escoand** [comment]
The version string of the snap is still old.

**Comment by kyrofa** [comment]
> The version string of the snap is still old.

Yeah, while the version of the snap is related to the contained version of Nextcloud, the snap's version isn't actually updated until that particular snap is released.

**Comment by kyrofa** [comment]
Logged https://github.com/nextcloud/contacts/issues/300 .

**Comment by pachulo** [comment]
Well, good news at last! I've modified the files modified in this PR https://github.com/nextcloud/server/pull/6332 in my snap (as commented here https://github.com/nextcloud/server/issues/6028) and the problem whit the spinning circle appearing before the configuration and the missing icons for the files app are gone!!

The fix should be applied in 12.0.4 but maybe we can convince them to apply it to 12.0.3...what do you think @kyrofa ?

**Comment by pachulo** [comment]
OK, I think that I made a mistake, I was not testing 12.0.1 but 11.0.4... @kyrofa could it be that right now this:

    $ sudo snap install nextcloud --channel=stable/pr-334

Installs the stable channel snap (revision #2707 as of now) and not the snap corresponding to this PR?

**Comment by kyrofa** [comment]
@pachulo ah indeed, they expire after a month and revert back to stable. Let me get them back up.

**Comment by pachulo** [comment]
Well, I just tried with:

    sudo snap install nextcloud --channel=12/edge

And then modified the files, but the issue is still there...guess it's time to go to bed :(

**Comment by kyrofa** [comment]
Ah darn, you got my hopes up! That fix didn't actually fix anything, then? Did you try the theming change suggested to regenerate the files?

**Comment by pachulo** [comment]
Yeah, it did not fix anything. Changing the color didn't help either.

**Comment by jospoortvliet** [comment]
12.0.3 is out, have had any luck here?

**Comment by kyrofa** [comment]
Hey @jospoortvliet, I'm afraid not. CSS is still broken, which rears its head in a number of ways, including: https://github.com/nextcloud/server/issues/6028 and https://github.com/nextcloud/server/issues/5532, and https://github.com/nextcloud/server/issues/5289 is concerning as well. You can test out the stable12 branch yourself with:

    sudo snap install nextcloud --channel=12/edge

**Comment by kyrofa** [comment]
No need to keep this open if we can't continue.

**Pull request closed without merging**
