### PR TITLE
Release 13.0.5snap1

### PR DESCRIPTION
**Pull request by kyrofa**
- php: update to 7.1.20
- nextcloud: update to 13.0.5
- apache: update to 2.4.34
- php: enable FTP support

### CODE REVIEW

**Comment by kyrofa** [comment]
Please test this PR out using the `candidate` channel:

    $ sudo snap install --candidate nextcloud

Or, if you already have it installed:

    $ sudo snap refresh --candidate nextcloud

@pachulo and @r4co0n, mind giving this a test on a fresh install as well as an upgrade from current `stable` and current `12/stable`?

**Comment by kyrofa** [comment]
This works for me, both as a fresh install, from `12/stable`, and from `stable`.

**Comment by pachulo** [comment]
I've tried both the upgrade from `stable` & the fresh install and everything went OK. I will try the `12/stable` when I can.

**Comment by kyrofa** [comment]
That's good enough for me @pachulo, I tested v12 to my satisfaction.

**Pull request merged**
