### PR TITLE
Release 13.0.4snap1

### PR DESCRIPTION
**Pull request by kyrofa**
- nextcloud: update to 13.0.4
- nextcloud: make cron interval adjustable
- mysql: don't consider mysql available until after restart
- mysql: update to 5.7.22
- many: implement static checks
- https: patch certbot to ignore system config

Test this release with the `candidate` channel:

    $ sudo snap install --candidate nextcloud

Or, if you already have it installed:

    $ sudo snap refresh --candidate nextcloud

### CODE REVIEW

**Comment by kyrofa** [comment]
@pachulo, @r4co0n please give this a test when you're able.

**Comment by pachulo** [comment]
Did the refresh from the current stable in my rbpi3 instance and everything went smooth.
System seems to be working fine too.

**Comment by bn4t** [comment]
Did the refresh from stable on my ubuntu 16.04 machine. Seems to be working fine too.

**Comment by r4co0n** [comment]
Did the refresh from stable on Debian 9/stretch, everything is working as expected.

**Comment by kyrofa** [comment]
Thank you all! I've also tested the fresh install as well as the upgrade, all seems well. Let's do this.

**Pull request merged**
