### PR TITLE
nextcloud: update to 16.0.5

### LINKED ISSUE #972: Update nextcloud to v16

### PR DESCRIPTION
**Pull request by kyrofa**
This PR resolves #972 by updating Nextcloud to the latest v16 release.

### CODE REVIEW

**Comment by kyrofa** [comment]
@pachulo, @r4co0n would appreciate your taking this for a spin.

**Comment by pachulo** [comment]
I would like to, but I'm running my instance on an arm64 installation, so I cannot test the snap builder snap...besides that, it is still at “Expected — Waiting for status to be reported” state, maybe there were some problems with it?

**Comment by kyrofa** [comment]
Don't worry, I built it for all architectures for exactly that reason.
Ignore the builder in this case :) .

**Comment by pachulo** [comment]
OK, did the refresh from 15.0.7 and everything went OK, but I've observed that some apps seem to be de-activated before being updated...and afterwards you need to activate them manually, including essential ones like “Calendar”.
Besides that, “End-To-End Encryption” seems to be not compatible yet: https://github.com/nextcloud/end_to_end_encryption/releases
Is that something we want to bear with?

**Comment by kyrofa** [comment]
Wait, so what, if you have encryption enabled and you upgrade, you just can't access stuff?

**Comment by pachulo** [comment]
Well, it should work anyway if activated manually:

- https://github.com/nextcloud/end_to_end_encryption/issues/108#issuecomment-493020190

but not the best experience IMHO...

**Comment by kyrofa** [comment]
Yeah that's not cool at all. Sounds like we agree we don't want to expose our users to that, so we're in a holding pattern for a bit. I'll release 15.0.8 while we wait.

**Comment by TarSzator** [comment]
Added a comment here, because we are still waiting for this issue right?
https://github.com/nextcloud/end_to_end_encryption/issues/108#issuecomment-505347157

**Comment by kyrofa** [comment]
Indeed, yes. It's been a long time since they release 16.0.1, too, I wonder if they're all focusing on something particular.

**Comment by kyrofa** [comment]
Alright folks (particularly @pachulo), let's test this again now that v16.0.2 is out. Ignore any errors from the snap builder, I built these all the old way for all architectures in the `beta/pr-1002` channel:

    $ sudo snap install nextcloud --channel=beta/pr-1002

Or, if you already have it installed:

    $ sudo snap refresh nextcloud --channel=beta/pr-1002

**Comment by pachulo** [comment]
Tested this and I'm still seeing the "Activate not tested apps" button for Calendar, Quota warning, Talk & End-to-End Encryption...I'm still not sure that this is what we want for our users, even though is not a fault of the snap.
At least for the first 3, updating them and reloading the page seems to get rid of the button, but in my case they needed to be re-activated anyway...how can this still be the case for such popular applications?

It's a real pity, because loading times of nextcloud 16.0.x seems to be lower than with 15.0.x

**Comment by kyrofa** [comment]
Actually, 16.0.2 is entirely busted due to https://github.com/nextcloud/server/issues/16238 . I'm not sure what's going on with quality control over there :disappointed: . Is "install, login, and attempt to upload something" not a part of the QA process before shipping the release? Guess we continue that holding pattern.

**Comment by kyrofa** [comment]
> At least for the first 3, updating them and reloading the page seems to get rid of the button [...]

I suspect that issue will go away if we can ship an updated v15 snap before updating to v16.

**Comment by manuee** [comment]
Hi, just wanted to point out that Nextcloud 15 end of life is scheduled for 2019-12:
https://docs.nextcloud.com/server/16/admin_manual/release_schedule.html

That said, thanks for playing it safe with this, makes me feel more confident on using the snap.

**Comment by kyrofa** [comment]
> Hi, just wanted to point out that Nextcloud 15 end of life is scheduled for 2019-12 [...]

Oh yeah, don't worry, we want to update to v16 as soon as possible! We just need a not-broken release first (that includes the apps being ready for it). I expect this will happen in the "weeks" timeframe-- we shouldn't even approach v15 end-of-life.

**Comment by manuee** [comment]
> > Hi, just wanted to point out that Nextcloud 15 end of life is scheduled for 2019-12 [...]
> 
> Oh yeah, don't worry, we want to update to v16 as soon as possible! We just need a not-broken release first (that includes the apps being ready for it). I expect this will happen in the "weeks" timeframe-- we shouldn't even approach v15 end-of-life.

Ah great to know, thanks!

**Comment by pachulo** [comment]
It seems that 16.0.3 & 15.0.10 are already here...

**Comment by pachulo** [comment]
Is this ready to test @kyrofa ?

**Comment by kyrofa** [comment]
@pachulo not yet, pause on this for the moment and let's focus on getting a v15 update out. Of course, that's not ready for a test yet either *cough* I hate infrastructure problems. I'll ping you!

**Comment by kyrofa** [comment]
Alright @pachulo, this is ready for a test. My testing shows that upgrading from 15.0.10 still shows calendar as incompatible, and then trying to update it still shows it as untested. This is _particularly_ weird if you install v16 fresh, without upgrading, where you can install the same version of the calendar app without any warning whatsoever. I'm not sure what's happening here.

**Comment by kyrofa** [comment]
> My testing shows that upgrading from 15.0.10 still shows calendar as incompatible [...]

To clarify this particular point, version 1.6.5 of the calendar app [supports both v14 and v15](https://github.com/nextcloud/calendar/blob/f38a828da32ab4dedbae28027e7337269e5962e4/appinfo/info.xml#L34). The calendar app didn't gain v16 compatibility until version 1.7.0, which is the same release where it [_dropped_ support for v15](https://github.com/nextcloud/calendar/blob/3bc261b629fd402727b0f9b8dc106e26069b2b62/appinfo/info.xml#L34), which means there's no release that gives us a bridge. There's no way we'll be able to push out v16 without the upgrade force-disabling the calendar app due to incompatibility.

@georgehrke, any chance the calendar app can see a release that supports both v15 and v16? Similarly, do you have any idea why updating to 16.0.3 from 15.0.10 and then updating the calendar app shows it as untested?

**Comment by pachulo** [comment]
So, do we have to test this @kyrofa ? Or do we wait till they figure a solution for the calendar app?

**Comment by kyrofa** [comment]
Honestly I'm not quite sure what to do here. I've [logged an issue](https://github.com/nextcloud/calendar/issues/1359) upstream, let's see what they think.

If they say no, I see two options here:

1. Push ahead with release knowing that it will disable anyone's calendar app and require that it be re-enabled.
2. Try to write a post-update process that will update and attempt to re-enable any disabled apps.

Neither of these options are ideal. Thoughts?

**Comment by the-sane** [comment]
I'm fairly new to Nextcloud, having only installed it via snap a few months ago, but my impression so far has been that the snap package prefers upgrades to be as seamless as possible for its users, ideally requiring no manual intervention to maintain current functionality.  Based on the info in the upstream issue, it sounds like that may not be possible in this situation.

If it's possible to write a script to handle this automatically, as in @kyrofa's point 2 above, that's the route I'd prefer to see happen on my own server during upgrades.  I don't have a problem with my apps being updated automatically for major releases (it's been requested before: https://github.com/nextcloud/nextcloud-snap/issues/978).  I also like the idea of the snap having a facility to handle this situation on its own in the future.  For some reason, I get the impression that this kind of thing might happen again.  I'm left feeling generally underwhelmed by the way the v16 release has been handled and I'm very glad I chose to install it via snap to have a team monitoring release stability for me before pushing out upgrades (thanks, guys!).

If that's not possible, then I'd consider notifications the second best option.  If there's any way to hook into Nextcloud's admin notifications and let people know "hey, sorry, but you'll need to re-enable some apps", that's what I'd be looking for as a server administrator.  I think it's okay to assume that a responsible administrator has configured key people to get those notifications and having the ability to push out snap-specific notifications seems like another good thing to have in general anyway.

**Comment by dmjohnsson23** [comment]
Chiming in here as a happy user excited to try out Nextcloud 16 and the new
text app.

Assuming the calendar app is the only thing holding this back, I personally
would be perfectly okay with even something as simple as a warning in the
terminal when I run `snap refresh` with a link to an article on what to do
after the update.

I suppose I can't speak for everyone in that, but that's my take. Obviously
it's best if everything magically works out of the box, but I would suppose
most users of Nextcloud would be technical enough to put in a little elbow
grease as long as they are notified what to do.

**Comment by kyrofa** [comment]
> I'm fairly new to Nextcloud, having only installed it via snap a few months ago, but my impression so far has been that the snap package prefers upgrades to be as seamless as possible for its users, ideally requiring no manual intervention to maintain current functionality.

Haha, it thrills me to no end that we've given that impression-- does that mean that we've succeeded? You're exactly right-- the entire purpose of the Nextcloud snap is to offer something as close to maintenance-free as possible without having to worry about also getting out-of-date. It automatically updates in order to meet these goals, which isn't responsibility we take lightly. When your users update automatically, you dang well better make sure you don't _break_ them automatically. Which is why this issue makes me crinkle my nose as much as it does.

> If it's possible to write a script to handle this automatically, as in @kyrofa's point 2 above, that's the route I'd prefer to see happen on my own server during upgrades.

I agree, I think that's really the only decent route forward. It's just going to take some work, which pushes v16 out further :tear: . The challenge is that apps are disabled as part of the upgrade process. We have no way of knowing if app X was disabled by the user or by the upgrade, so we can't just update and re-enable everything. This will require some work to check the state of things before and after the upgrade and not try and mess up the setup the user had before the upgrade took place.

**Comment by the-sane** [comment]
I suspect the work will have future payoffs, and everyone will appreciate the stability guarantees that come with it.  What about hooking into the notifications system?  Even if you're able to accomplish this, there's always the potential for something to go awry in some edge-cases.  I know I would appreciate a little notification showing up urging me to double check that all my app updates went smoothly.

**Comment by kyrofa** [comment]
> What about hooking into the notifications system?

I've looked into it in the past-- I just wanted to be able to say "Hey admins, Nextcloud updated, if anything broke you know there to go" etc. However, there's no way to send a notification to a group, which means we'd need to loop through all users (which is paginated, even on the CLI), determine which ones are admins, and then send them each the notification. I agree it'd be a great feature, but I judged the rewards not enough to justify the effort, at least for me. I'd totally be up for reviewing a PR though if you think there's value in it.

**Comment by ryanprior** [comment]
It sounds like we're exposing a number of shortcomings in the platform overall. Maybe we can put together an overall design document describing what we want, and what obstacles are in the way, so we can present that as a cohesive whole rather than a collection of isolated repo issues?

**Comment by the-sane** [comment]
@kyrofa What about using the Announcements system instead of the Notifications system? (https://github.com/nextcloud/nextcloud_announcements)

This is configurable in the admin settings and should handle the "send to group" part for you?
Screenshot_2019-07-15 Settings - Nextcloud

**Comment by thelovebug** [comment]
How about a release in the 16/beta channel for those who don't mind about the apps being disabled?  We have to manually refresh to 16/beta anyway as it doesn't exist currently 😁

**Comment by stondino00** [comment]
> How about a release in the 16/beta channel for those who don't mind about the apps being disabled? We have to manually refresh to 16/beta anyway as it doesn't exist currently 😁


I agree.  Let's keep a release of 16 current for those who don't mind moving to 16 now and keeping up on all the security updates of the dependencies.

I've had 0 issues upgrading from version 15 to the latest pr-1002 and do not use the calendar app.

**Comment by kyrofa** [comment]
> How about a release in the 16/beta channel for those who don't mind about the apps being disabled?

> I agree. Let's keep a release of 16 current [...]

Oh by all means, [that's exactly what `16/candidate` is for](https://github.com/nextcloud/nextcloud-snap/issues/972#issuecomment-495356382). `16/edge` are daily builds for v16 as well, if you're interested in that:

```
$ snap info nextcloud
name:      nextcloud
<snip>
channels:
  <snip>
  16/stable:    –                                          
  16/candidate: 16.0.3snap1rc1    2019-07-15 (14625) 227MB -
  16/beta:      ↑                                          
  16/edge:      16-2019-07-14     2019-07-14 (14606) 227MB -
  <snip>
```

**Comment by srottschaefer** [comment]
I've been using the snapped version of Nextcloud for about 9 months now and I am really satisfied with how little maintenance is required to keep it running. I think you can be really proud of that.
The only thing I have to do manually is updating my apps and I wouldn't mind that being taken care of as well :smile:.
That being said, [the argument in the auto update feature request](https://github.com/nextcloud/server/issues/15360#issuecomment-490392453) is valid in my opinion and updating apps blindly (even only the enabled ones) might cause problems to people.
Maybe we could have a configuration option to enable/disable auto updating (3-way switch: enabled/disabled/required).
When setting up their Nextcloud snap people need to read a bit of documentation in order to get HTTPS and stuff running. A little extra explanation for an auto-update switch probably won't hurt.
Adding a disclaimer that enabling it might break exotic app configurations might also help.

Some piece of extra information in case you haven't seen it yet: [Nextcloud 16 should already check for required app updates](https://github.com/nextcloud/server/issues/15416#issuecomment-511775111).

I would love to help out but at the moment I don't think I have the required knowledge to provide code, especially ruby tests for it.
All I can offer for now is my experience and opinion on the matter :sweat_smile: hope that helps as well.

**Comment by kyrofa** [comment]
> Some piece of extra information in case you haven't seen it yet: Nextcloud 16 should already check for required app updates.

That's news to me, I might owe you a beer for the work you just saved.

**Comment by dmjohnsson23** [comment]
To be honest I wasn't even aware my Nextcloud was auto-updating until now, so I guess that says something about how historically awesome you guys have been about not breaking things.

I decided to try the 16/candidate channel and thought I'd just share my experience.

Immediately after the update, the web interface was really buggy. The page kept crashing and over all pretty much nothing worked. I looked in the browser console and saw a couple deprecation warnings as well as a whole bunch of 404 errors. However, after logging out and waiting about 5 minutes everything started working and I haven't had a single problem since, so I'll just chalk it up to maybe there was still some post-install script running the first time I logged in. This was a couple days ago.

As expected, the Calendar app had to be manually updated before it would work. This was also the case with the AppOrder app.

So yeah, I don't know that the Nextcloud 16 update is "install automatically for everyone" ready yet, but I would definitely say it's 100% "opt-in a click a few buttons" ready. It's been stable and fully functional for me the past couple days at least.

**Comment by kyrofa** [comment]
> To be honest I wasn't even aware my Nextcloud was auto-updating until now, so I guess that says something about how historically awesome you guys have been about not breaking things.

Aw, everyone is so nice in this thread! I appreciate everyone chiming in :) .

> Immediately after the update, the web interface was really buggy. The page kept crashing and over all pretty much nothing worked. I looked in the browser console and saw a couple deprecation warnings as well as a whole bunch of 404 errors. However, after logging out and waiting about 5 minutes everything started working and I haven't had a single problem since, so I'll just chalk it up to maybe there was still some post-install script running the first time I logged in. This was a couple days ago.

That sounds weird, I wonder if your browser was using cached assets. The cache should be busted by the upgrade, but I'm not completely up to speed on how that works, maybe the cron job does it at some point which is why it was only fixed later. That said, I've not seen this in my (admittedly limited) v16 testing. Anyone else?

**Comment by the-sane** [comment]
> Anyone else?

No issues here other than the known calendar breakage.  It's been smooth sailing once I realized what was going on with that.  Could it be browser-specific?  I'm using Firefox for Linux.

**Comment by dmjohnsson23** [comment]
I was using a Chromebook when I performed the update, when everything was
broke. I can't remember for sure whether the second login when everything
worked fine was still in the Chromebook, or whenever I had switched myself
into business mode and moved over to my Linux desktop and Firefox at that
point. (I move between the two pretty regularly on any given day.)

As I mentioned before though, the issue is totally gone now, and everything
works great for me in both browsers, so I would tend to think it just had
something it was still finishing up from the install the first time. I was
feeling a little over-excited at the time and logged in about half a second
after the update finished, because I'm an abnormal human being like that.

I just figured I would let you guys know how the update went just in case
it might be helpful, but if no one else can reproduce it I personally am
not too worried about it. After all, it did resolve itself after a few
minutes. Who knows, it could have even just been a network glitch.

**Comment by srottschaefer** [comment]
I planned on upgrading to v16/candidate this weekend. If I have any news I am letting you know.

**Comment by pachulo** [comment]
OK, updated my instance and, taking out the know issues with the calendar app not updating, everything seems quite smooth! I could not reproduce what @dmjohnsson23 experienced.

**Comment by srottschaefer** [comment]
I've been on 16/candidate for 2 days without any trouble. I could not test the Calendar app issue since I don't have it installed and forgot to do so before the update *shame on me*. I got a few "Enable untested" warning buttons for already updated apps after the update to 16 but a restart of the snap got rid of those. Something probably got stuck there.

**Comment by auberginepop** [comment]
Smooth update here (with manual app updates).
Running for second day without any issues.

**Comment by derhagen** [comment]
Running 16/candidate for 2 weeks now. no problems after manually updating some apps

**Comment by alexander-rieder** [comment]
also running 16/candidate for some weeks without a problem

**Comment by alexander-rieder** [comment]
any news?

**Comment by the-sane** [comment]
This is the upstream pull request we're all waiting on: https://github.com/nextcloud/server/pull/16507

**Comment by stondino00** [comment]
Has 16/candidate been updated with php 7.2.21?

**Comment by stondino00** [comment]
Please upgrade this 16/candidate channel with the latest 16.0.4.  It contains security fixes.

https://github.com/nextcloud/server/releases/tag/16.0.4

ALSO please include the latest PHP 7.2.21 which includes security fixes as well.

**Comment by stondino00** [comment]
Please update apache http in 16/candidate to 2.4.41.  This fixes vulnerabilities.

https://github.com/apache/httpd/releases/tag/2.4.41

**Comment by kyrofa** [comment]
That one has landed, so now we're waiting on the backport to v16: https://github.com/nextcloud/server/pull/16753.

**Comment by stondino00** [comment]
Can we try out 16.0.4 in this channel?  I'm not showing any issues so far with php 7.2.21 and apache 2.4.41 with nextcloud 16.0.3.  Thanks

**Comment by the-sane** [comment]
@stondino00  He's trying very hard to get the needed upstream fix into 16.0.4 so that it can go to the stable channel when it's released.

**Comment by kyrofa** [comment]
> He's trying very hard to get the needed upstream fix into 16.0.4 [...]

16.0.5 now :cry: .

**Comment by alexander-rieder** [comment]
so what is the roadmap? Can i help in any way?

**Comment by Bleuzen** [comment]
Can the 16/candidate channel be updated with 16.0.4 for now? It is still on 16.0.3.

**Comment by kyrofa** [comment]
Alright, that PR was finally merged upstream, just waiting for 16.0.5 now.

**Comment by kyrofa** [comment]
Ah, it's beautiful, got a preview using `16/edge` (daily v16 builds):

    $ sudo snap install nextcloud

(install calendar app)

    $ sudo snap refresh nextcloud --channel=16/edge

```
$ journalctl -f -u snap.nextcloud.apache.service
<snip>
Sep 06 15:36:37 protege nextcloud.apache[460]: Disabled incompatible app: calendar
<snip>
Sep 06 15:36:42 protege nextcloud.apache[460]: Checking for update of app calendar in appstore
Sep 06 15:36:42 protege nextcloud.apache[460]: Update app calendar from appstore
Sep 06 15:36:44 protege nextcloud.apache[460]: Checked for update of app "calendar" in appstore
```

**Comment by pachulo** [comment]
Thanks a lot for this @kyrofa !

**Comment by pachulo** [comment]
Is this real life? XD
https://github.com/nextcloud/server/releases/tag/v16.0.5

**Comment by kyrofa** [comment]
Alright folks, despite what the Snap Builder says, this is ready for testing on all supported architectures:

    $ sudo snap install nextcloud --channel=beta/pr-1002

Or if you already have it installed:

    $ sudo snap refresh nextcloud --channel=beta/pr-1002

It seems to pass muster as far as I can see-- apps are finally updated properly, including calendar and contacts. Anyone see anything broken?

**Comment by markmcb** [comment]
Looks good to me. No issues with calendar or contacts.

**Comment by pachulo** [comment]
Did the refresh from 16.0.4snap1rc1 and everything is working OK!
Now even the Bookmarks app works again (it stopped working with the last update).

**Comment by the-sane** [comment]
The only issue I've had with v16 in general is the missing toolbar in the new text app under dark mode, as mentioned in https://github.com/nextcloud/nextcloud-snap/issues/902#issuecomment-518315948, caused by our old friend "ResourceLocator cannot find a web root": https://github.com/nextcloud/server/issues/13556

**Comment by kyrofa** [comment]
@the-sane thanks for the heads up. As that app is only supported on v16 I don't consider it a regression, and thus it should not hold this up, do you agree?

I think this is ready for merge, but I'll wait until @the-sane confirms everything is okay.

**Comment by the-sane** [comment]
@kyrofa I agree, it shouldn’t hold anything up right now. I don’t believe that app is the default text editor yet, but it seems that’s the eventual plan so I wanted to make sure it’s on the radar.

**Comment by kyrofa** [comment]
>@kyrofa I agree, it shouldn’t hold anything up right now.

Alright, shipping then.

**Comment by emansije** [comment]
This morning I was happy to find that my NC had upgraded to version 16.0.5snap1 (16232) (I'm using the stable channel) but then I found out that the contacts app stopped working. :disappointed: 
The log shows this message:

```
ResourceLocator can not find a web root (root: /var/snap/nextcloud/16232/nextcloud/extra-apps/contacts, file: index.php/css/contacts/1e49-afb2-contacts.css?v=d41d8cd98f00b204e9800998ecf8427e, webRoot: , throw: true)
```

**Comment by kyrofa** [comment]
@emansije my contacts app is working fine-- can you please log an issue with what exactly is happening?

**Comment by emansije** [comment]
Sure. It's #1130

**Comment by Browniver** [comment]
@kyro thanks for the update! I refreshed to beta and this reduced some of the error-messages in my logs from "resourceLoacator [...] web root" but still having issues. Dont know what "spree" app is. However for calendar, contacts & tasks the beta solved the issues. 

`

Error | lib | ResourceLocator can not find a web root (root: /var/snap/nextcloud/16199/nextcloud/extra-apps/spreed, file: index.php/css/spreed/41bb-650b-merged-files.css?v=d41d8cd98f00b204e9800998ecf8427e, webRoot: , throw: true) |   | 2019-10-03T12:30:32+0200
-- | -- | -- | -- | --
Error | lib | ResourceLocator can not find a web root (root: /var/snap/nextcloud/16199/nextcloud/extra-apps/spreed, file: index.php/css/spreed/41bb-650b-merged-files.css?v=d41d8cd98f00b204e9800998ecf8427e, webRoot: , throw: true) |   | 2019-10-03T12:28:03+0200
Error | lib | ResourceLocator can not find a web root (root: /var/snap/nextcloud/16199/nextcloud/extra-apps/spreed, file: index.php/css/spreed/41bb-650b-merged-files.css?v=d41d8cd98f00b204e9800998ecf8427e, webRoot: , throw: true) |   | 2019-10-03T12:28:03+0200
Error | lib | ResourceLocator can not find a web root (root: /var/snap/nextcloud/16233/nextcloud/extra-apps/spreed, file: index.php/css/spreed/41bb-650b-merged-files.css?v=d41d8cd98f00b204e9800998ecf8427e, webRoot: , throw: true)

`

**Pull request merged**
