### PR TITLE
nextcloud: update to 20.0.1

### LINKED ISSUE #1474: Update Nextcloud to v20
v20.0.0 was just released. We'll wait until at least the point release to upgrade everyone, but time to start the process.

### PR DESCRIPTION
**Pull request by kyrofa**
This PR resolves #1474 by updating Nextcloud to v20. Note that this will not be merged until at least the first point release, but this gives us a place to gather feedback.

### CODE REVIEW

**Comment by kyrofa** [comment]
Wow this is quite a different release, I'll need to rewrite some of the tests as a result.

**Comment by kyrofa** [comment]
Builds of this PR are available for all architectures in the `latest/beta/pr-1475` channel:

    $ sudo snap install nextcloud --cannel=latest/beta/pr-1475

Or, if you already have it installed (don't do this on a production install though):

    $ sudo snap refresh nextcloud --channel=latest/beta/pr-1475

**Comment by kyrofa** [comment]
Most apps appear to work fine. Sadly I am unable to open any files-- whenever I click on anything it just shows a spinner forever and the javascript console shows:

```
 Opening viewer for file  /Nextcloud Manual.pdf Viewer.vue:227
08:20:27.219 Uncaught (in promise) TypeError: OCA.Theming is undefined
    updateTitle Viewer.vue:458
    n Viewer.vue:336
    l runtime.js:63
    _invoke runtime.js:293
    v runtime.js:118
    ae viewer-main.js:403
    a viewer-main.js:403
    se viewer-main.js:403
    se viewer-main.js:403
    openFile Viewer.vue:309
    file Viewer.vue:228
    VueJS 10
    value Viewer.js:133
    N FilesActionHandler.js:36
    action merged-index.js:2921
    _onClickFile merged-index.js:4787
    Underscore 3
    jQuery 2
Viewer.vue:458
```

Can anyone else confirm?

**Comment by kyrofa** [comment]
Ah, things start working if I enable the Theming app. I logged this as https://github.com/nextcloud/server/issues/23198 upstream. @kesselb FYI.

**Comment by Pilzinsel64** [comment]
Yesterday I updated my existing instance (yes, productive private, but I can't wait and can revert if I have problems). However, everything seems to work fine for me so far. I will notify you if I find any problems!

**Comment by kyrofa** [comment]
Thanks for testing, @Pilzinsel64! You're correct about the snap using 7.3, but we're aware of the passwords app. Keep an eye on #1477, we'll try to roll that out before upgrading to v20.

**Comment by kyrofa** [comment]
Alright, just tested 20.0.1, it seems to work great. Fixes the one problem I ran into with 20.0.0. Works well both as a fresh install and as an upgrade from stable.

**Pull request merged**
