### PR TITLE
Snap usage example for php configuration

### PR DESCRIPTION
**Pull request by eespitiarea**
Given the comments and questions posted in this [issue](https://github.com/nextcloud/nextcloud-snap/issues/77), I think including an example of how to use snap to setup php values would ease configuration.

### CODE REVIEW

**Comment by kyrofa** [comment]
Thank you for working to improve our documentation, however, the documented functionality doesn't actually exist, nor is the unrelated documentation correct (e.g. you can upload > 2GB on 32-bit, try it).

**Comment by eespitiarea** [comment]
@kyrofa, couple of comments:

1. Took the info from https://docs.nextcloud.com/server/14/admin_manual/configuration_files/big_file_upload_configuration.html, does that means that section is outdated or is just not applicable here?
2. How is it that `sudo snap set nextcloud php.upload-max-filesize=16G` does change the settings persistently while using `nextcloud.occ` doesn't?

Appreciate your comments, just trying to understand.

**Comment by worikgh** [comment]
This is effecting me too
I have a snap installation of next cloud
I can upload a 1M file but not a 2M file/.
I cannot find any logs anywhere lohhing errors but using the webdav interface I get `HTTP Error: Request Entity Too Large` error.  
This fits with what apears to be in the php.ini files:
```
# find  /snap/nextcloud/ -name "php.ini" -exec grep -Hni upload_max_filesize '{}' \;
/snap/nextcloud/13968/config/php/php.ini:802:upload_max_filesize = 2M
/snap/nextcloud/14509/config/php/php.ini:802:upload_max_filesize = 2M
```
I ran the command `snap set nextcloud php.upload-max-filesize=16G` to no effect.
Is there really no way to change settings like this?
2M is really very small these days.

**Comment by kyrofa** [comment]
> [...] does that means that section is outdated or is just not applicable here?

Indeed, that's not applicable to the snap.

> How is it that sudo snap set nextcloud php.upload-max-filesize=16G does change the settings persistently while using nextcloud.occ doesn't?

`sudo snap set nextcloud php.upload-max-filesize=16G` does absolutely nothing. It's part of the functionality that, as I mentioned, doesn't actually exist. I have no idea where you got it, or what gives you the impression it has any effect. All the configuration capable via `snap set` is [explicitly documented](https://github.com/nextcloud/nextcloud-snap#configuration).

**Comment by kyrofa** [comment]
@worikgh I've never run into that limit. Any chance you have a proxy or some other piece of tech sitting in front of the snap on the network?

**Comment by worikgh** [comment]
This is effecting me too
I have a snap installation of next cloud
I can upload a 1M file but not a 2M file/.
I cannot find any logs anywhere lohhing errors but using the webdav interface I get `HTTP Error: Request Entity Too Large` error.  
This fits with what apears to be in the php.ini files:
```
# find  /snap/nextcloud/ -name "php.ini" -exec grep -Hni upload_max_filesize '{}' \;
/snap/nextcloud/13968/config/php/php.ini:802:upload_max_filesize = 2M
/snap/nextcloud/14509/config/php/php.ini:802:upload_max_filesize = 2M
```
I ran the command `snap set nextcloud php.upload-max-filesize=16G` to no effect.
Is there really no way to change settings like this?
2M is really very small these days.

**Comment by worikgh** [comment]
I am proxying through nginx.  I see no reason why that should have a effect, but maybe.
Are you saying that you use snap-nextcloud's file uploading interface for large files (over 2M)?

Today I am rebuilding from something other than snap, where I have control over all the parameters. If I remember to I will report I solve the problem.

**Comment by worikgh** [comment]
I have installed next cloud from source in a container
I adjusted the php `upload_max_filesize` to 2000M
Still can not upload a 2M file, but can upload a 1M file.
I am proxying through `nginx` with...
```
        location / {
                 proxy_pass http://<local IP of container>;
                 proxy_set_header Host $host;
        }
```

I do not think the proxying is the problem.  But I have been wrong in the past....

**Comment by worikgh** [comment]
1M seems to be the limit.
I have tried 1.1M (and 2M, 1.5 and 1.25) all have same error

**Comment by worikgh** [comment]
Egg on my face!
The problem *was* the nginx proxy.
Changing the configuration `client_max_body_size` to a large value fixed it.  By default it barfs at 1M
Golly!

**Comment by kyrofa** [comment]
Yeah that's the exact config value I was going to suggest taking a look at. Glad you got it solved.

**Pull request closed without merging**
