### PR TITLE
Change Nextcloud version in README

### PR DESCRIPTION
**Pull request by MariusBluem**
Finally 🙌 

cc @kyrofa @oparoz

### CODE REVIEW

**Comment by kyrofa** [comment]
*Ahem* I seem to have missed that one, so sorry!

Thanks for the PR, but please target this to develop instead of master (as noted in the [contribution guide](https://github.com/nextcloud/nextcloud-snap/blob/master/CONTRIBUTING.md)). As soon as that's done I'll accept.

**Comment by kyrofa** [comment]
(Please also push to a fork instead of the main project).

**Comment by MariusBluem** [comment]
Sorry ... Did not know about the special guidelines applying here 😁 ...will change this ✊

**Comment by MariusBluem** [comment]
...i've changed the base branch to `develop` so this should be fine now 😉 You could simply reopen this PR and merge it ... or does it need to be a fork? 😁 I will do this in the future for PRs submitted to `nextcloud-snap` but I cannot see any downsides of ignoring this for this PR here 😜 @kyrofa

**Comment by MariusBluem** [comment]
Done with #107 😜

**Pull request closed without merging**
