### PR TITLE
nextcloud: update to 11.0.4

### LINKED ISSUE #335: Update to 11.0.4
Hi guys,
As soon as v12 is too buggy, could we try 11.0.4?

### PR DESCRIPTION
**Pull request by kyrofa**
Nextcloud v12 is pretty buggy. This PR resolves #335 by updating the snap to v11.0.4 while we're trying to stabilize. Please test this PR by using the `stable/pr-338` channel:

    $ sudo snap install nextcloud --channel=stable/pr-338

Or if you already have it installed:

    $ sudo snap refresh nextcloud --channel=stable/pr-338

### CODE REVIEW

**Comment by kyrofa** [comment]
This seems to work quite nicely for me. @pachulo, what do you think? @SkyWheel if you could give this a test as well I'd appreciate it.

**Comment by SkyWheel** [comment]
@kyrofa ,
I have access only to my web page till 21st of August when I'll return back to my city.
If it's possible I will try to get remote access to the server to test this release.
Thank you.

**Comment by pachulo** [comment]
I seems to work OK in my rbpi3 instance @kyrofa ...but I had to disable and enable the snap after the update, because the apache httpd did not go up....I'm not really sure if it's something related to the nextcloud update.

**Comment by kyrofa** [comment]
It worked alright here. I'd be curious to see the log when something like that happens, it means our upgrade process isn't as robust as I'd like, which I know, but it'd give me some insight as to why (mine never fails). Regardless, I think this is okay.

**Pull request merged**
