### PR TITLE
exposed nextcloud documents through content interface

### PR DESCRIPTION
**Pull request by rmescandon**
Sharing documents through content interface.
Needed for collabora office snap (code) to communicate to nextcloud

### CODE REVIEW

**Comment by kyrofa** [comment]
Please read the [contributing guide](https://github.com/nextcloud/nextcloud-snap/blob/master/CONTRIBUTING.md). I prefer to have discussions on bugs before you go to the work of making a PR. I think [I mentioned this on your last PR](https://github.com/nextcloud/nextcloud-snap/pull/182#issuecomment-274229392).

**Comment by rmescandon** [comment]
Sorry @kyrofa, you're completely right. I forgot to file a related bug. 
Fixes [#216] [1]

[1] https://github.com/nextcloud/nextcloud-snap/issues/216

**Comment by kyrofa** [comment]
> This should not be merged. We should never give access to the data folder to outside apps.

Note that this interface is not connected unless the user explicitly does so. But yes, I'm not a fan of this either. Since there's conflicts here anyway I'll go ahead and close this. We can continue discussions on the bug as necessary.

**Comment by oparoz** [comment]
> Note that this interface is not connected unless the user explicitly does so.

Yes, I should have been clearer. The problem is more that it breaks Nextcloud.

**Pull request closed without merging**
