### PR TITLE
Update PHP to the latest 7.2 release

### LINKED ISSUE #617: Update PHP to 7.2.x
It seems that Nextcloud 13.x supports PHP 7.2.x:

- https://docs.nextcloud.com/server/13/admin_manual/installation/system_requirements.html

And as per this comparison, it seems that the overall performance should be a little bit better:

- https://www.phoronix.com/scan.php?page=news_item&px=PHP-7.2-Benchmarks-RC6

### PR DESCRIPTION
**Pull request by pachulo**
Now that we are on Nextcloud 14 we can start to test this.

This PR resolves #617

### CODE REVIEW

**Comment by kyrofa** [comment]
This doesn't run, I'm afraid. I suspect you need to update the php.ini, [here](https://github.com/nextcloud/nextcloud-snap/blob/master/src/php/config/php.ini#L726) specifically.

**Comment by pachulo** [comment]
Damn, I always forget about the change in the API date...Thanks!

**Comment by pachulo** [comment]
OK, now the failure is for the test that checks the PHP string in debug mode:
```
Failures:

  1) Change operating mode debug
     Failure/Error: expect(response["x-powered-by"]).to match /PHP\/7\.1\.\d+/
     
       expected "PHP/7.2.14" to match /PHP\/7\.1\.\d+/
       Diff:
       @@ -1,2 +1,2 @@
       -/PHP\/7\.1\.\d+/
       +"PHP/7.2.14"
```
Nothing important I guess...

**Comment by kyrofa** [comment]
Go ahead and fix that test, then-- check for 7.2 instead of 7.1

**Comment by kyrofa** [comment]
Please test this PR using the `beta/pr-840` channel:

    $ sudo snap install nextcloud --channel=beta/pr-840

Or, if you already have it installed:

    $ sudo snap refresh nextcloud --channel=beta/pr-840

**Comment by kyrofa** [comment]
Upstream says user_saml is fixed, and we're not getting any testers that have the app, which means this will need to turn into a bit of a scream test (although I'm pretty confident this is fine these days, I can install the app for example).

**Pull request merged**
