### PR TITLE
nextcloud: update to 13.0.6

### LINKED ISSUE #695: Update nextcloud to 13.0.6
https://nextcloud.com/changelog/#latest13

### PR DESCRIPTION
**Pull request by bn4t**
Fixes #695

### CODE REVIEW

**Comment by bn4t** [comment]
````
Sorry, Snapcraft ran into an error when trying to running through its lifecycle that generated a trace that has been put in '/tmp/tmp3s04jj0v/trace.txt'.

"Submitting this error to the Snapcraft developers is not possible through the CLI without Raven installed.

If you wish to report this issue, please copy the contents of the previous traceback and submit manually at https://launchpad.net/snapcraft/+filebug.

Exited with code 1
````

Weird error. Going to try and run it again.

**Comment by bn4t** [comment]
Not sure why exactly it's failing. Tested it on a local machine and didn't got the error.

````
Priming setup-https 

Sorry, Snapcraft ran into an error when trying to running through its lifecycle that generated a trace that has been put in '/tmp/tmp2hx6nqez/trace.txt'.

"Submitting this error to the Snapcraft developers is not possible through the CLI without Raven installed.

If you wish to report this issue, please copy the contents of the previous traceback and submit manually at https://launchpad.net/snapcraft/+filebug.

Exited with code 1
````

**Comment by bn4t** [comment]
Is there any way to look at the saved stacktrace of the build? @kyrofa

**Comment by kyrofa** [comment]
> Is there any way to look at the saved stacktrace from the build?

I'm afraid not, the new release of snapcraft started hiding that. I've pushed a new commit to ask it to stop.

**Comment by kyrofa** [comment]
#698 should "fix" the build error. Once that merges we can remove the commit I pushed here, update, and all should be right with the world.

**Comment by kyrofa** [comment]
Alright this should be fixed, now. I've removed my commit, as well as the one that updates the version (that only happens upon release). We'll be able to take it for a spin soon.

**Comment by bn4t** [comment]
Cool, thanks for helping out!

**Comment by pachulo** [comment]
@kyrofa can you set up a channel to test this out?
Thanks!

**Comment by bn4t** [comment]
Cool, thanks for merging! :+1:

**Pull request merged**
