### PR TITLE
apache: remove extra semicolon from hsts header

### PR DESCRIPTION
**Pull request by bn4t**
This is suggested by hstspreload.org

hstspreload.org

### CODE REVIEW

**Comment by kyrofa** [comment]
Note that #426 is not an issue, so putting a `Solves` there has no meaning.

Also, please take a quick look at some other commits here. Notice the title structure generally follows a `<subsystem>: <summary>` structure. Mind updating this commit to reflect? Perhaps `apache: remove extra semicolon from hsts header` (no period).

Thank you!

**Comment by bn4t** [comment]
I readjusted the commit title. 

Also, I created the issue #426 as suggested by the contribution guideline. That's why I mentioned it.

I'm sorry for all the additional paperwork I'm creating. Should have look into the contribution guideline before submitting a PR.

**Comment by kyrofa** [comment]
Whoops, my mistake, you're right-- thank you for creating #426! Indeed, so the commit message should look something like this:

```
apache: remove extra semicolon from hsts header

Solves #426
```

Note that your amend/squash or whatever you did didn't quite workout correctly since it looks like you squashed onto a merge commit already in `develop` instead of your own commit. Mind taking a look?

**Comment by bn4t** [comment]
I messed up the squashing gonna open up a new PR. shit.

**Comment by kyrofa** [comment]
For what it's worth, I find the whole squashing/rebasing thing a lot easier if you create a feature branch instead of committing straight to develop.

**Comment by bn4t** [comment]
Ok, gonna do that in the new PR.

**Pull request closed without merging**
