### PR TITLE
nextcloud: update to 18.0.4

### LINKED ISSUE #1247: Upgade to Nextcloud 18
Dear all, if i want to update the app to 18.0 Nextcloud Hub, i use sudo snap nextcloud refresh (at host machine of course), it return with the result of nothing to update. I been told it was because the latest snap stable is stucked at 16.0.8. So if i want to change to 18 (edge) version, can i do the following?

Current Ver. of NC: 16.0.8
Ubuntu Server w. LXDE skin.
Nextcloud install with Snap.

I would backup my data directory and just uninstall my current nextcloud and reinstall with Vers. 18 Nextcloud Hub Snap and replace the new data directory with my old data directory.

Will that worked?

### PR DESCRIPTION
**Pull request by kyrofa**
This PR resolves #1247 by updating Nextcloud to the latest v18 release.

### CODE REVIEW

**Comment by kyrofa** [comment]
Completely untested. Let's see how it looks.

**Comment by kyrofa** [comment]
@pachulo I built this for all architectures in `beta/pr-1271` if you would like to test it out.

**Comment by Leptopoda** [comment]
Works eine for me (other than the json issue)
Can I help testing anything specific/ is there any specific testing procedure? I can't find anything in the wiki

**Comment by kyrofa** [comment]
@Leptopoda we have a set of smoke tests [outlined here](https://github.com/nextcloud/nextcloud-snap/wiki/Smoke-Tests) if you're looking for specific things to test.

**Comment by pachulo** [comment]
Well, everything seems quite functional!

I've seen these errors on the log though (apart from our friends `ResourceLocator can not find a web root`):
```
[PHP] Error: Undefined variable: result at /snap/nextcloud/19385/htdocs/apps/serverinfo/lib/OperatingSystems/DefaultOs.php#173
GET /index.php/settings/admin/serverinfo
from 10.1.1.215 by admin at 2020-02-28T22:49:28+00:00
[PHP] Error: Invalid argument supplied for foreach() at /snap/nextcloud/19385/htdocs/apps/serverinfo/templates/settings-admin.php#101
GET /index.php/settings/admin/serverinfo
from 10.1.1.215 by admin at 2020-02-28T22:49:29+00:00
[PHP] Error: Invalid argument supplied for foreach() at /snap/nextcloud/19385/htdocs/apps/serverinfo/lib/Os.php#155
GET /ocs/v2.php/apps/serverinfo/api/v1//diskdata?format=json
from 10.1.1.215 by admin at 2020-02-28T22:49:30+00:00
```
But to me they are only side effects from the confinement of the snap that materialize when visiting the status in the admin area, because this is what I see there:
```
Sistema Operatiu:
Processador: ( cores)
```

**Comment by kyrofa** [comment]
Alright, 18.0.4 is in `beta/pr-1271` for all architectures. Please [give it a test](https://github.com/nextcloud/nextcloud-snap/wiki/Testing-pull-requests) and let us know what you think!

**Comment by derhagen** [comment]
> Alright, 18.0.4 is in `beta/pr-1271` for all architectures. Please [give it a test](https://github.com/nextcloud/nextcloud-snap/wiki/Testing-pull-requests) and let us know what you think!

Not sure if this is an issue on my side or if it has something to do with the failed snap building task:
```
# snap refresh nextcloud --channel=beta/pr-1271
error: requested a non-existing branch for snap "nextcloud": 18/beta/pr-1271
```

Is `snap info nextcloud` supposed to list this pull request? Because it doesn't. I'm on `18/edge` FYI.

**Comment by pachulo** [comment]
> Not sure if this is an issue on my side or if it has something to do with the failed snap building task:

I faced the same issue, but it worked for me after using `latest/beta/pr-1271` as name channel.

> Is snap info nextcloud supposed to list this pull request?

It's expected that this `pr-x channel`s are not showed there.

**Comment by pachulo** [comment]
Well, everything seems smooth here with the update!

@kyrofa it looks like @kesselb PR https://github.com/nextcloud/server/pull/19084 won't be merged till, at least, when 19 is released, but I would say that's not blocking.

By the way, I really love the new Photos app!

**Comment by kyrofa** [comment]
> I faced the same issue, but it worked for me after using latest/beta/pr-1271 as name channel.

How interesting, that's news to me. It works on a fresh install, but it sounds like it uses your current track all of a sudden instead of latest by default? I'll update the wiki directions.

I agree @pachulo, no need to block on that.

**Comment by derhagen** [comment]
> Alright, 18.0.4 is in `beta/pr-1271` for all architectures. Please [give it a test](https://github.com/nextcloud/nextcloud-snap/wiki/Testing-pull-requests) and let us know what you think!

I upgraded my existing instance from 18/edge to this PR. A quick check shows everything is working as expected.

**Comment by kyrofa** [comment]
Seems to work well both as a fresh install (with and without recommended apps) as well as an upgrade from stable. Let's ship this. Thanks testers!

**Pull request merged**
