### PR TITLE
nextcloud: update to 19.0.12

### LINKED ISSUE #1663: nextcloud: update to 19.0.12
https://nextcloud.com/changelog/#latest19

### PR DESCRIPTION
**Pull request by pachulo**
Resolve #1663

### CODE REVIEW

**Review by caugner — APPROVED** [review]
LGTM

**Comment by pachulo** [comment]
Hi @kyrofa ! I really think we should offer an update to those users of stable/19 channel; the last one is from December...do you want me to update this PR to 19.0.12?

**Comment by kyrofa** [comment]
Hey @pachulo, agreed, I'm sorry. Please do bring it up to date and let's get it out there.

**Comment by pachulo** [comment]
> Hey @pachulo, agreed, I'm sorry.

Please, don't be! I mean, the support we get from you regarding the snap excels and I'm very grateful for that!

> Please do bring it up to date and let's get it out there.

Done!

**Comment by caugner** [comment]
@pachulo I think you need to sign off your commit to make DCO happy, see details here: https://github.com/nextcloud/nextcloud-snap/pull/1664/checks?check_run_id=2747837537

As for the failed circleci build, I think this was only a temporary failure, but I just triggered a re-run to make sure.

**Comment by caugner** [comment]
> As for the failed circleci build, I think this was only a temporary failure, but I just triggered a re-run to make sure.

Hm, same failure again: 

```
Fetching godeps...
go get -d github.com/rogpeppe/godeps
/snap/bin/go: 5: exec: /snap/go/current/command-go.wrapper: not found
Failed to run 'go get -d github.com/rogpeppe/godeps' for 'mdns-publisher': Exited with code 127.
Verify that the part is using the correct parameters and try again.

Exited with code exit status 2

CircleCI received exit code 2
```

See: https://github.com/nextcloud/nextcloud-snap/pull/1689

@kyrofa Should we cherry-pick 2e77f5a23edcf85848694a6e0b79b7fce0bda99c into this PR, should we create a separate PR for backporting this to the `19` branch?

**Comment by kyrofa** [comment]
Yeah we need to backport that fix, separate PR, please.

**Comment by kyrofa** [comment]
@pachulo please rebase on the latest and CI should run successfully again.

**Comment by pachulo** [comment]
Done!

**Pull request merged**
