### PR TITLE
nextcloud: update to 17.0.5

### LINKED ISSUE #1277: Update NextCloud to 17.0.5
https://nextcloud.com/changelog/#latest17

https://nextcloud.com/blog/18-0-2-17-0-4-and-16-0-9-are-here-update-time/

### PR DESCRIPTION
**Pull request by kyrofa**
This PR resolves #1277 by updating Nextcloud to the latest v17 release.

### CODE REVIEW

**Comment by stondino00** [comment]
Thanks Kyrofa!  I don't think it successfully built however.

**Comment by kyrofa** [comment]
_**grumble grumble** need to rewrite that thing_

**Comment by pachulo** [comment]
Can we test this using the beta channel then @kyrofa ?

**Comment by kyrofa** [comment]
Yeah I'll need to build it the old way. Not sure what the deal is with the builder, I'll look into it later. Hang tight and I'll let you know when it's up.

**Comment by kyrofa** [comment]
Alright, ignore the snap builder, a snap for this PR is in `beta/pr-1288`.

**Comment by kyrofa** [comment]
Works for me, both fresh install and upgrade from stable.

**Pull request merged**
