### PR TITLE
nextcloud: update to 15.0.4

### LINKED ISSUE #889: Update nextcloud to 15.0.4

### PR DESCRIPTION
**Pull request by kyrofa**
This PR resolves #889 by updating Nextcloud to the latest v15 release.

Please test this PR using the `beta/pr-890` channel:

    $ sudo snap install nextcloud --channel=beta/pr-890

Or, if you already have it installed:

    $ sudo snap refresh nextcloud --channel=beta/pr-890

### CODE REVIEW

**Comment by bn4t** [comment]
Took it for a spin. Seems to work fine. Didn't encounter any errors.

**Comment by pachulo** [comment]
Tested the refresh (by the way, there's a typo in the command @kyrofa ) in my rbpi instance and everything seems alright, except for all the know issues with 15.x: https://github.com/nextcloud/server/milestone/73
Thanks!

**Comment by kyrofa** [comment]
@pachulo would you say one of the issues you listed would make for a regression from what we have today?

**Comment by pachulo** [comment]
No, I would say there are regressions from what was present in 14, but not compared to 15.0.2

**Comment by gcollura** [comment]
Works for me too! Thank you

**Pull request merged**
