### PR TITLE
Release 16.0.8snap1

### PR DESCRIPTION
**Pull request by kyrofa**
- nextcloud: update to 16.0.8
- hooks: add pre-refresh hook to update apps
- php: update to 7.3.14
- nextcloud: notify admins upon update
- mysql: update to 5.7.29

### CODE REVIEW

**Comment by kyrofa** [comment]
Tested fresh install as well as upgrade. Everything looks good.

**Comment by pachulo** [comment]
Is there any problem with builds for arm*? I can see the update yet on my arm64 instance

**Comment by kyrofa** [comment]
*ahem* yes the problem was me, please try again.

**Comment by pachulo** [comment]
Much better now! Installed and running fine, this afternoon will try the update to v17 from https://github.com/nextcloud/nextcloud-snap/pull/1224 and will report there!

**Pull request merged**
