### PR TITLE
Nextcloud: update to 13.0.4

### LINKED ISSUE #594: Update Nextcloud to 13.0.3

### PR DESCRIPTION
**Pull request by pachulo**
This PR resolves #594

### CODE REVIEW

**Comment by kyrofa** [comment]
A snap of this PR has been released into the `beta/pr-595` channel.

**Comment by kyrofa** [comment]
This seems to work fine, although the upgrade process has actually resulted in #196 twice in a row (from stable to this channel). Can anyone else duplicate?

**Comment by pachulo** [comment]
Hey @kyrofa they just released 13.0.4:

- https://github.com/nextcloud/server/milestone/43?closed=1

What should we do?

**Comment by kyrofa** [comment]
Oh, that was fast. Might as well update to that one instead.

**Comment by kyrofa** [comment]
We need #608 before this one, I'm afraid. I think it's actually due to the mysql change.

**Pull request merged**
