### PR TITLE
php: update to 7.3.14

### LINKED ISSUE #1230: Update PHP to 7.3.14
https://www.php.net/ChangeLog-7.php#7.3.14

Contains security fixes

### PR DESCRIPTION
**Pull request by kyrofa**
This PR resolves #1230 by updating PHP to the latest 7.3 release.

### CODE REVIEW

**Comment by stondino00** [comment]
No issues so far after refreshing from beta. Thanks

**Comment by kyrofa** [comment]
Hmm... one of our test tools is failing (not due to anything we did). Investigating now...

**Comment by stondino00** [comment]
No issues for me after a few days of running this PR with 16.0.7.

**Comment by kyrofa** [comment]
Alright, I think I've fixed the test failure here (due to still running in on Trusty, darn Circle CI).

**Pull request merged**
