### PR TITLE
Increase PHP and Apache proxy timeout to 3600 seconds.

### PR DESCRIPTION
**Pull request by kyrofa**
Image verification noted a failure to upload 1.5GB file on rpi2, logs indicated a timeout occurred.

### CODE REVIEW

**Comment by oparoz** [comment]
AFAIK, this needs to match what's in the Apache config. Is it also set at 3600?

**Comment by kyrofa** [comment]
> AFAIK, this needs to match what's in the Apache config. Is it also set at 3600?

To which parameter in the Apache config are you referring?

**Comment by oparoz** [comment]
https://github.com/nextcloud/nextcloud-snap/blob/master/src/apache/conf/httpd.conf#L149

**Comment by kyrofa** [comment]
Good catch @oparoz, thank you!

**Pull request merged**
