### PR TITLE
Upgrade MySQL to 8.0.26

### LINKED ISSUE #1795: Upgrade MySQL to 8.0.26
Releasing today with Oracle's quarterly patch schedule.  Contains security fixes.

### PR DESCRIPTION
**Pull request by stondino00**
Fixes #1795

### CODE REVIEW

**Comment by kyrofa** [comment]
Does this require GCC 8, now?

**Comment by stondino00** [comment]
> Does this require GCC 8, now?

Yeah I believe your correct on this.

image

**Comment by kyrofa** [comment]
Alright I just pushed an update adding gcc and g++ 8, let's see if CI is happier.

**Comment by stondino00** [comment]
> Alright I just pushed an update adding gcc and g++ 8, let's see if CI is happier.

Awesome

Thanks

**Pull request merged**
