### PR TITLE
nextcloud: update to 14.0.5

### LINKED ISSUE #706: Update to Nextcloud 14
As Nextcloud 14 has been released, could we update the beta/stable channels to this release?

### PR DESCRIPTION
**Pull request by kyrofa**
This PR resolves #706 by updating Nextcloud to v14.0.5.

Please test this PR using the `beta/pr-799` channel:

    $ sudo snap install nextcloud --channel=beta/pr-799

Or, if you already have it installed:

    $ sudo snap refresh nextcloud --channel=beta/pr-799

### CODE REVIEW

**Comment by kyrofa** [comment]
This seems to work well from my perspective. Tested file upload, contacts, calendar, and theming.

**Comment by kyrofa** [comment]
Upgrade from stable succeeds, although it does end up with the following warnings:

screenshot from 2018-11-25 16-14-29

Ignore the HTTP one, I just didn't set it up for this instance. The PHP memory limit is expected; we only set it to 512MB on new installs, existing installs will need to tweak it manually if it's what they want. The fact that indices are missing seems silly to me, but we can probably fix it ourselves after maintenance mode is removed after the initial upgrade, I'll experiment with it.

**Comment by fishscene** [comment]
In the release notes, we can probably add something like: 
"The recommended PHP memory limit has changed to 512MB. If you are upgrading an existing Nextcloud snap, please update your PHP memory limit to 512MB or higher with the following command:"
`sudo snap set nextcloud php.memory-limit=512M`

Forcing this change may cause existing servers to crash.

As for the database indexes, anything that can be done to automate this would be awesome, but I'm completely unfamiliar with how Snaps work and how this could be automated. Just my 2 cents I guess. :)

Thanks Kyrofa!

**Comment by pachulo** [comment]
Refreshed my instance with this channel and hit that bug with some icons of the files app not showing:
captura de pantalla de 2018-11-27 08-28-23

captura de pantalla de 2018-11-27 08-29-43

Is anybody else experiencing this?

**Comment by srottschaefer** [comment]
> Refreshed my instance with this channel and hit that bug with some icons of the files app not showing:
> captura de pantalla de 2018-11-27 08-28-23
> 
> captura de pantalla de 2018-11-27 08-29-43
> 
> Also tested it with a fresh install on my laptop...is anybody else experiencing this?

This already happens with 14/candidate for me. Should we open a new issue?

**Comment by pachulo** [comment]
@kyrofa do you think that it could be related to this bug? https://github.com/nextcloud/server/issues/12290

**Comment by kyrofa** [comment]
Yeah kinda looks like it anyway, not 100% sure.

**Comment by pachulo** [comment]
I don't really know what's going in here. I've just compared a local installation of nextcloud with a demo server, and the URIs seem to be OK:
captura de pantalla de 2018-12-01 20-08-46
But in the snap it's returning a 404...besides that, the file seems to be where is ought to:
```
$ sudo find /snap/nextcloud/current/ -iname tag.svg
/snap/nextcloud/current/htdocs/apps/systemtags/img/tag.svg
```

**Comment by kyrofa** [comment]
The fix has [been proposed](https://github.com/nextcloud/server/pull/13224).

**Comment by kyrofa** [comment]
Alright, 14.0.5RC1 is now available in `14/candidate`, please give it a try! Everything looks good to me so far.

**Comment by kyrofa** [comment]
> I had to restart nextcloud after updating the apps, because the Bookmarks app was in "disabled" state and I could not change it.

Huh, yeah that's odd. If you look at the upgrade log you'll see `Disabled incompatible app: bookmarks` like they did back in the v11 days. It's because that version of bookmarks isn't compatible with v14, only v13. However, once you complete the update, you can go to Apps -> Updates, update the app, and then enable it (without restarting, although oddly I had to refresh before the Enable button would make itself clickable). I'm not sure why the upgrade process doesn't just do the upgrade for you like the other apps. This seems like an upstream bug, but not a blocker, I think?

**Comment by pachulo** [comment]
@kyrofa for me, the Bookmarks App update "problem" is not a blocker, it's something that will happen with snap or without it.

**Comment by kyrofa** [comment]
Very good. I updated `14/candidate` with this current PR (but using the RC), which should fix the indices automatically. I've given this some pretty thorough testing, I'm pretty confident. Release is slated for Thursday.

**Comment by brainfrz82** [comment]
I jumped the gun and updated to 14/candidate. All seems well. Only thing i stubled upon is my shared links are changed. Previously https://nextcloud.hostname.eu/index.php/s/secretid/authenticate was working just fine, but with nextcloud 14 it redirects to the main login form. The link https://nextcloud.hostname.eu/index.php/s/secretid (so without the /authenticate part) is working as expected. Might be an upstream change, and no big deal. So just an heads-up here.

**Comment by kyrofa** [comment]
Huh, very interesting. Indeed, that must be an upstream change.

**Comment by kyrofa** [comment]
Alright guys, this is updated and ready to go-- give it one last test!

    $ sudo snap install nextcloud --channel=beta/pr-799

Or, if you already have it installed:

    $ sudo snap refresh nextcloud --channel=beta/pr-799

**Comment by pachulo** [comment]
Everything went fine here with the refresh! Glad to see this finally coming!

**Comment by kyrofa** [comment]
Finally!

**Pull request merged**
