### PR TITLE
Use full path to mysqld

### PR DESCRIPTION
**Pull request by samtygier**
Fix for #745

### CODE REVIEW

**Comment by samtygier** [comment]
On Debian the snap is not confined, so calling mysqld can start /usr/sbin/mysqld causing nextcloud to fail to start #745 

Not tested, but maybe this is along the right lines.

**Comment by samtygier** [comment]
This is not sufficient to fix the issue. The main mysqld process is started from src/mysql/support-files/mysql.server but that looks like it is doing the paths correctly.

**Comment by kyrofa** [comment]
Thanks @samtygier, but the whole point of snaps is to be cross-distro. If they aren't, that's a bug in snapd or snapcraft, not this snap. I'd rather try to figure out what's broken in those then try to work around it here, it doesn't scale.

**Comment by samtygier** [comment]
Thanks, that makes sense. Have you opened a bug in snapd/snapcraft?

**Pull request closed without merging**
