### PR TITLE
Update Nextcloud 21.0.2

### LINKED ISSUE #1736: Upgrade Nextcloud 21.0.2
Nextcloud releasing 21.0.2 today.

https://nextcloud.com/changelog/#latest21

### PR DESCRIPTION
**Pull request by stondino00**
Fixes #1736

### CODE REVIEW

**Comment by szaimen** [comment]
There is a problem with the built-in pdfviewer:
https://github.com/nextcloud/files_pdfviewer/issues/381

**Comment by stondino00** [comment]
Currently not being addressed by developers it appears.  Blog post is recommending 21.0.2.  Let's see if something comes about first of next week on this issue I guess.

https://nextcloud.com/blog/21-0-2-20-0-10-and-19-0-11-are-available-prepare-to-update-beta-1-for-22-is-also-out-so-you-can-help-test/

**Comment by stondino00** [comment]
Looks like it won't get fixed until next minor release.  There is a manual way to fix it it appears.

🩹 Temporary fix (will be shipped in the next Nextcloud minor release only)
ℹ️ This is a temporary fix you can apply manually, from PR #384. To do this:
1) Replace the file at apps/files_pdfviewer/js/files_pdfviewer-main.js on your instance with this file from that PR
2) Clear your (each user must do it) browser's cache and try to open pdfs. This is a must-do, otherwise, the old file will be loaded from browser's cache !!

**Comment by kyrofa** [comment]
Yeah let's skip and wait for the fix.

**Comment by stondino00** [comment]
Waiting for 21.0.3 to fix this bug

**Pull request closed without merging**
