### PR TITLE
nextcloud: update to 13.0.2

### LINKED ISSUE #439: Update Nextcloud to 13.0.1

### PR DESCRIPTION
**Pull request by kyrofa**
This PR resolves #439 by updating Nextcloud to v13.0.2. Please test using the `13/candidate` channel:

    $ sudo snap install nextcloud --channel=13/candidate

Or, if you already have it installed:

    $ sudo snap refresh nextcloud --channel=13/candidate

### CODE REVIEW

**Comment by QuaySo** [comment]
I tested on a fresh install and so far no big issues to report.
Only noticed that the background job setting was on `AJAX` where I expected `CRON`. Changed that to `CRON` and saw the job running every 15 minutes.

**Comment by kyrofa** [comment]
Try removing and re-installing, and then leave the background job setting alone. It _should_ change to cron automatically within 15 minutes. Can you verify?

**Comment by QuaySo** [comment]
You're right. It changed automatically to `CRON`.

**Comment by kyrofa** [comment]
Ah very good, thank you!

**Comment by pachulo** [comment]
Well, updated my rbpi3 installation and it seems that it worked OK:

- Applications are all enabled.
- The date seems to be all there.

But I'm seeing funny things in the interface, like these:

image

image

image

And in the DevTools of Chrome I'm seeing this error:

`Refused to apply style from 'http://10.1.1.234/index.php/apps/files/' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.`

**Comment by chrauscher** [comment]
the correct command for upgrading is

$ sudo snap refresh nextcloud --channel=13/candi**d**ate

**Comment by kyrofa** [comment]
> the correct command for upgrading is

*cough* oh whatever are you talking about? 😉

**Comment by chrauscher** [comment]
I'm having the same stylesheet issue as @pachulo
`Resource interpreted as Stylesheet but transferred with MIME type text/html`

**Comment by QuaySo** [comment]
No interface glitches here on a fresh install on Ubuntu 17.10 server.
What is your config?

**Comment by chrauscher** [comment]
Ubuntu 16 LTS and install via snap. Nothing fancy.

**Comment by kyrofa** [comment]
I'm not seeing these issues on Firefox. I'd try Chrome, but I'm rendering a video right now and it's 50/50 whether chrome crashes X, so I'll do that later. Note that I DO see the star in the contacts app, but I think that's just a new feature (the ability to set favorites) rather than a weird UI thing.

**Comment by kyrofa** [comment]
Ah, wait-- I DO see those weird issues _if I upgrade_ instead of fresh install.

**Comment by chrauscher** [comment]
Something like this?

image

**Comment by kyrofa** [comment]
Yeah, fresh install looks like this (note how the checkbox is not only vertically aligned, but also horizontally aligned with the master checkbox above).

screenshot from 2018-02-09 14-49-14

**Comment by chrauscher** [comment]
Maybe it is related to this issue https://github.com/nextcloud/server/issues/8279

**Comment by kyrofa** [comment]
Nice catch! Indeed, running these commands and then reloading the page seems to fix things:

```
# rm -r /var/snap/nextcloud/common/nextcloud/data/appdata_*/css/* /var/snap/nextcloud/common/nextcloud/data/appdata_*/js/*
# nextcloud.occ files:scan-app-data

Scanning AppData for files

+---------+-------+--------------+
| Folders | Files | Elapsed time |
+---------+-------+--------------+
| 10      | 4     | 00:00:00     |
+---------+-------+--------------+
```

**Comment by kyrofa** [comment]
Rather than make everyone do that, I think we'll wait for 13.0.1, which already has the fix.

**Comment by chrauscher** [comment]
I'm having issues with the external storage settings after installing nextcloud 13. I cannot configure any external storage, the page is empty.

**Comment by ainslied** [comment]
Hi, the same as chrauscher for me.
The external storage settings page is empty, but the titles row appears (just before the new content loading) when you jump to an other page (as if the page was waiting for the end of a javascript things or something like this before showing the entire table; this waiting seems to be interrupted when moving to an other page).
chrauscher, do you know if this append when you do a fresh install with snap of 13/candidate directly?

**Comment by ainslied** [comment]
Here is a extract of inspector in firefox :
snap

**Comment by chrauscher** [comment]
I have installed nextcloud directly, no upgrade was made.

**Comment by jasper321** [comment]
i'm not able to change my login wallpaper, the same for the logo
image

**Comment by enoch85** [comment]
Just to confirm: https://github.com/nextcloud/server/issues/8043#issuecomment-362073432

It's a bug which is fixed in 13.0.1

**Comment by kyrofa** [comment]
> The external storage settings page is empty, but the titles row appears (just before the new content loading) when you jump to an other page (as if the page was waiting for the end of a javascript things or something like this before showing the entire table; this waiting seems to be interrupted when moving to an other page).
chrauscher, do you know if this append when you do a fresh install with snap of 13/candidate directly?

It happens on a fresh install for me, exactly as you describe.

**Comment by kyrofa** [comment]
> It happens on a fresh install for me, exactly as you describe. No idea what's happening there, wonder if it's a problem with the app.

@chrauscher, @ainslied I just tried to poke that this issue today and suddenly can't reproduce it. Perhaps the external storage app was updated. Can you two please try again?

**Comment by skjnldsv** [comment]
> The external storage settings page is empty, but the titles row appears (just before the new content loading) when you jump to an other page (as if the page was waiting for the end of a javascript things or something like this before showing the entire table; this waiting seems to be interrupted when moving to an other page).
> chrauscher, do you know if this append when you do a fresh install with snap of 13/candidate directly?

Bug in the app, fixed in https://github.com/nextcloud/server/pull/8511
You need to create ext storage in your admin settings or allow users to create some.

**Comment by ainslied** [comment]
Ok, nice !
I did several weeks ago `sudo snap install nextcloud` to install the v.12, then `sudo snap install nextcloud --channel=13/candidate` to update to the v13.
Do you know what I have to do to update the snap and take into account the patch?
I tried `sudo snap refresh nextcloud --channel=13/candidate` but it says `no updates available`

**Comment by kyrofa** [comment]
> Bug in the app, fixed in nextcloud/server#8511

Thank you for letting us know, @skjnldsv! Really appreciate the info and the patch.

>  Do you know what I have to do to update the snap and take into account the patch?

The backport to v13 hasn't landed yet, but it's in the 13.0.1 milestone.

**Comment by kyrofa** [comment]
Hey folks, the fixes for all the issues discovered here should be contained in the `13/edge` channel. Mind testing that out?

**Comment by paschalis-ch** [comment]
Hello all

I have install the nextcloud 13 snap and now I would like to configer the server so that http will redirect permanently to https. I know, there are a lot of manuals in nextcloud communities but with a snap install, I don't know where I have to do the configuration.
Thanks for your support

**Comment by kyrofa** [comment]
Happy to help, but please open an issue so we don't dilute this PR.

**Comment by fishscene** [comment]
Login page image fixed when using edge channel.

In Ubuntu 17.10.1 Desktop, I ran:
`sudo snap install nextcloud --channel=13/candidate`
After configuring the theme, The login page was 100% stock.
The logo works only after logging in.
`sudo snap refresh nextcloud --channel=13/edge`
Logo and background image work in login page. Everything looks hunky-dory theming-wise. It even kept my logo when I refreshed to the edge channel.

I am very pleased by this as this has been a long-standing issue and it looks like it is addressed now. :)

**Comment by kyrofa** [comment]
Hey folks, 13.0.1 is now in the `13/candidate` channel, mind taking it for a spin? This is the candidate for our next stable release. In my testing I've uncovered both good news and bad news.

Good news:
- External storage seems to work fine
- Upgrade from v12 no longer garbles the layout

Bad news:
- Theming managed to break again

I know the bad news is bad, but since it's the current status quo in v12 I don't see it as a blocker to the upgrade. I don't really have the manpower to continually fix the same problem upstream... anyone else feel like taking a look at that one? Otherwise I'll do it when I have time. It must have been a recent change given @fishscene's feedback a week ago.

**Comment by PnjDbq** [comment]
Just tried the 13.0.1 candidate (`sudo snap refresh nextcloud --channel=13/candidate`) and encountered the CSS issue.

I'm using external storage, so the commands to fix were slightly different: 
`rm -r /media/externalUSB/nextcloud/data/appdata_*/css/*`  (and the JS folder also)
versus 
`rm -r /var/snap/nextcloud/common/nextcloud/data/appdata_*/css/*`.

No issues with the manual refresh other than needing to specify the different file path. 

For what it's worth, can also confirm the known theming issues.

**Comment by pachulo** [comment]
Just updated my rbpi to 13/candidate with the 13.0.1snap1-rc1 and everything went smooth! I'm not using any theme though, but I can also confirm that the layout mangling is not happening anymore when upgrading from 12.

**Comment by kyrofa** [comment]
Thanks for testing this out, @PnjDbq, I was just able to duplicate your results: if your data is stored in e.g. /media instead of the default location, the CSS fix shipped in 13.0.1 doesn't work. I'm not sure why, I'll look into it.

**Comment by PnjDbq** [comment]
Unexpected observation on the background image missing when using custom theme issue...

I was following #486 about maintenance mode.  When the server is in maintenance mode the background image becomes visible.  When maintenance mode is off and the server is running the background image goes missing.

**Comment by skjnldsv** [comment]
Cache clear force pull request is here: https://github.com/nextcloud/server/pull/8999 :)

**Comment by kyrofa** [comment]
@PnjDbq something is odd here. You mentioned that you ran into the CSS issue with `13/candidate`, but that removing the CSS and JS files (like before) fixed things. I just tried doing the same thing and I'm getting internal server errors now because Nextcloud keeps trying to open JS files. Any chance you can re-verify the steps you took?

To be clear, there's still a problem here in that the styles are somehow messed up when you put the data in /media somewhere, but the workaround you suggested does not seem to work.

**Comment by PnjDbq** [comment]
Just checked `.bash_history` and it looks like I didn't use the wildcard as suggested.  

Exact commands (as root) were:
```
rm -r /media/externalUSB/nextcloud/data/appdata_oc3a25k79enn/css/
rm -r /media/externalUSB/nextcloud/data/appdata_oc3a25k79enn/js/
nextcloud.occ files:scan-app-data
```
Running 13.0.1snap1-rc1 on Ubuntu 16.04.4 LTS 

Just re-ran commands without any issue (didn't need to, but also didn't get JS errors).

**Comment by pachulo** [comment]
The RC1 for 13.0.2 is out, but installing `13/edge` snap from `13-2018-04-18` should be more or less equivalent...Are there still problems with the sytles?

**Comment by pachulo** [comment]
Well, just updated to the `edge` channel (`13-2018-04-22` right now) and tried to change the theme:

- The image I set for the login page is showed OK.
- The image I set for the logo is showed OK.
- The color was also changed.

Also, the CSS problems I observed seem to be gone...Can anyone else try if all this is really solved with 13.0.2 so the update can move on? Thanks!

**Comment by QuaySo** [comment]
@pachulo : I upgraded to `edge` without problems and see no CSS problems. It would be nice to move on to 13.0.2!  ;-)

**Comment by kyrofa** [comment]
@pachulo did you try this with data in /media?

**Comment by pachulo** [comment]
No, i did not.

El dv., 27 abr. 2018, 16:39, Kyle Fazzari <notifications@github.com> va
escriure:

**Comment by kyrofa** [comment]
Yeah, it's still busted with it in `/media`.

**Comment by kyrofa** [comment]
Ah ha, @PnjDbq the key seems to be `nextcloud.occ files:scan-app-data`, using that fixes things here.

**Comment by kyrofa** [comment]
Good news folks: @skjnldsv figured this out and has fixed it in https://github.com/nextcloud/server/pull/9367.

**Comment by FoxBJK** [comment]
Working on my install, also includes Calendar and Contacts (caldav and carddav). All seems OK so far.

**Comment by kyrofa** [comment]
Just testing theming, too-- it works! I'm shipping this.

**Pull request merged**
