### PR TITLE
nextcloud: update to 15.0.6

### PR DESCRIPTION
**Pull request by stondino00**
Bugfix update for 15.0.5

### CODE REVIEW

**Comment by kyrofa** [comment]
Please take a quick look at the [contribution guide](https://github.com/nextcloud/nextcloud-snap/blob/master/CONTRIBUTING.md); issues need to be created, then pull requests with commits properly referencing the issues.

That said, this release is weird, how did you find it? It was tagged a few hours ago, but nextcloud.com is still pointing to 15.0.5. The PR seems fine (other than the issue/commit items I mentioned), but let's hold off on landing it until Nextcloud itself is actually recommending it.

**Comment by stondino00** [comment]
My apologies for not creating an issue first.

It's in their releases for server and was scheduled for release today but they have not updated the changelog accordingly.  They'll probably do this tomorrow I would assume.

https://github.com/nextcloud/server/releases

I'll make sure I create an issue first next time.  Thanks

**Comment by kyrofa** [comment]
Excellent. Thanks for being so on top of things.

**Comment by kyrofa** [comment]
Had a chat with upstream today, it seems there's a critical sharing bug in 15.0.6 which is why they haven't recommended it yet. Closing this in favor of waiting for 15.0.7.

**Pull request closed without merging**
